const DATA=window.QUIZ_DATA;
const STATIC_DATA=window.STATIC_SOLUTION_DATA;
const SOLUTIONS=STATIC_DATA?.solutions||{};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const WRONG_STORAGE_KEY='networkQuizWrongV1';
const LAST_STORAGE_KEY='networkQuizLast';
const SOURCE_PAGE_IMAGES={1:'assets/source-page-01.png',10:'assets/source-page-10.png',19:'assets/source-page-19.png',21:'assets/source-page-21.png',49:'assets/source-page-49.png',56:'assets/source-page-56.png'};
const state={pool:[],idx:0,answered:{},score:0,mode:'normal',lastPoolIds:[],currentView:'study'};

function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function validateStaticSolutions(){if(!STATIC_DATA||STATIC_DATA.metadata?.question_count!==DATA.metadata.question_count)throw new Error(`Thiếu dữ liệu lời giải tĩnh: cần ${DATA.metadata.question_count} câu.`);const missing=DATA.questions.filter(q=>!SOLUTIONS[q.id]).map(q=>q.id);if(missing.length)throw new Error(`Thiếu lời giải tĩnh cho ${missing.length} câu: ${missing.slice(0,10).join(', ')}`);for(const q of DATA.questions){const s=SOLUTIONS[q.id];if(!Array.isArray(s.options)||s.options.length!==q.options.length)throw new Error(`Lời giải tĩnh không đủ phương án: ${q.id}`)}}

function setup(){
  try{validateStaticSolutions()}catch(e){document.body.innerHTML=`<main class="wrap"><div class="card"><h2>Không thể mở bộ đề</h2><p>${escapeHtml(e.message)}</p><p>Trang không tự sinh lời giải thay thế. Hãy sửa dữ liệu tĩnh trước khi học.</p></div></main>`;throw e}
  const set=$('#setSelect');DATA.metadata.sets.forEach(s=>set.add(new Option(`${s.name} (${s.count} câu)`,s.id)));set.add(new Option(`Tất cả (${DATA.metadata.question_count} câu)`,'ALL'),0);set.value=DATA.metadata.sets[0].id;set.onchange=buildChapters;buildChapters();
  const mistakeFilter=$('#mistakeSetFilter');DATA.metadata.sets.forEach(s=>mistakeFilter.add(new Option(s.name,s.id)));
  $('#startBtn').onclick=start;$('#prevBtn').onclick=()=>move(-1);$('#nextBtn').onclick=()=>move(1);$('#retryWrong').onclick=retryWrong;$('#resetBtn').onclick=resetProgress;$('#unansweredBtn').onclick=goToNextUnanswered;$('#paletteToggleBtn').onclick=togglePalette;$('#toggleSetupBtn').onclick=toggleSetup;$('#resumeMistakesBtn').onclick=()=>reviewSavedMistakes();$('#againBtn').onclick=restartLastPool;$('#summaryWrongBtn').onclick=retryWrong;$('#summarySavedWrongBtn').onclick=()=>setView('mistakes');$('#reviewFilteredMistakesBtn').onclick=()=>reviewSavedMistakes(getFilteredMistakeIds());$('#clearMistakesBtn').onclick=clearMistakeBank;mistakeFilter.onchange=renderMistakes;$('#mistakeSearch').oninput=renderMistakes;
  $$('[data-view]').forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.view)));
  document.addEventListener('keydown',handleKeyboard);window.addEventListener('hashchange',syncViewFromHash);
  updateMistakeBadge();renderMistakes();syncViewFromHash();
}

function buildChapters(){const s=$('#setSelect').value,ch=$('#chapterSelect');ch.innerHTML='<option value="ALL">Tất cả chương</option>';const vals=[...new Set(DATA.questions.filter(q=>s==='ALL'||q.set===s).map(q=>q.chapter).filter(Boolean))];vals.forEach(v=>ch.add(new Option(v,v)))}
function start(){let p=DATA.questions.filter(q=>($('#setSelect').value==='ALL'||q.set===$('#setSelect').value)&&($('#chapterSelect').value==='ALL'||q.chapter===$('#chapterSelect').value));const term=$('#searchInput').value.trim().toLowerCase();if(term)p=p.filter(q=>(q.question+' '+q.options.map(o=>o.text).join(' ')).toLowerCase().includes(term));if($('#shuffleQ').checked)p=shuffle(p);beginPool(p,'normal')}
function beginPool(pool,mode='normal'){state.pool=[...pool];state.idx=0;state.answered={};state.score=0;state.mode=mode;state.lastPoolIds=pool.map(q=>q.id);setView('study',false);$('#emptyState').classList.add('hidden');$('#quizArea').classList.remove('hidden');$('#questionCard').classList.remove('hidden');$('#questionSidebar').classList.remove('hidden');$('#summaryCard').classList.add('hidden');$('#againBtn').classList.remove('hidden');$('#summaryWrongBtn').classList.remove('hidden');if(!pool.length){showEmptyPool();return}render();scrollQuestionTop()}
function showEmptyPool(){$('#questionCard').classList.add('hidden');$('#questionSidebar').classList.add('hidden');$('#summaryCard').classList.remove('hidden');$('#summaryText').textContent='Không tìm thấy câu hỏi phù hợp với bộ lọc hiện tại.';$('#againBtn').classList.add('hidden');$('#summaryWrongBtn').classList.add('hidden');$('#summarySavedWrongBtn').classList.remove('hidden');updateStats()}
function optionOrder(q){if(!state.answered[q.id]?.order){state.answered[q.id]=state.answered[q.id]||{};state.answered[q.id].order=$('#shuffleA').checked?shuffle(q.options.map(o=>o.id)):q.options.map(o=>o.id)}return state.answered[q.id].order}

function render(){
  const q=state.pool[state.idx];if(!q){showEmptyPool();return}
  $('#questionCard').classList.remove('hidden');$('#questionSidebar').classList.remove('hidden');$('#summaryCard').classList.add('hidden');
  const ans=state.answered[q.id];$('#qPos').textContent=`Câu ${state.idx+1}/${state.pool.length}`;$('#qSource').textContent=`${state.mode==='mistakes'?'Ôn câu sai • ':''}${q.set} • câu gốc ${q.source_number} • trang ${q.source_page}`;$('#qText').textContent=q.question;
  const badge=$('#statusBadge');badge.className='badge '+q.verification;badge.textContent=q.verification==='corrected'?'Đã sửa đáp án':q.verification==='warning'?'Cần lưu ý':'Đã đối chiếu';const warn=$('#warningBox');warn.textContent=q.warning||'';warn.classList.toggle('hidden',!q.warning);renderSourceImage(q);
  const byId=Object.fromEntries(q.options.map(o=>[o.id,o])),box=$('#options');box.innerHTML='';optionOrder(q).forEach((id,i)=>{const o=byId[id],b=document.createElement('button');b.className='option';b.type='button';b.innerHTML=`<span class="letter">${letters[i]}</span><span class="option-copy">${escapeHtml(o.text)}</span><span class="keycap">${i+1}</span>`;b.onclick=()=>choose(q,id);if(ans?.selected){b.disabled=true;if(id===q.correct_option_id)b.classList.add('correct');if(id===ans.selected&&id!==q.correct_option_id)b.classList.add('wrong')}box.appendChild(b)});
  showFeedback(q,ans);updateStats();renderQuestionPalette();$('#prevBtn').disabled=state.idx===0;$('#nextBtn').textContent=state.idx===state.pool.length-1?'Xem kết quả':'Câu tiếp →';
}
function sourceImageFor(q){if(q.image)return q.image;const dependsOnVisual=/hình|sơ đồ|cửa sổ|diagram|figure/i.test(q.warning||'');return dependsOnVisual?SOURCE_PAGE_IMAGES[q.source_page]||null:null}
function renderSourceImage(q){const wrap=$('#sourceImageWrap'),img=$('#sourceImage'),link=$('#sourceImageLink'),src=sourceImageFor(q);if(src){img.src=src;img.alt=`Ảnh/trang đề gốc - ${q.set}, câu ${q.source_number}, trang ${q.source_page}`;link.href=src;wrap.classList.remove('hidden')}else{wrap.classList.add('hidden');img.removeAttribute('src');link.removeAttribute('href')}}
function choose(q,id){if(state.answered[q.id]?.selected)return;state.answered[q.id].selected=id;const correct=id===q.correct_option_id;if(correct){state.score++;removeMistake(q.id,false)}else recordMistake(q);render();saveProgress()}
function chooseByPosition(pos){const q=state.pool[state.idx];if(!q||state.answered[q.id]?.selected)return;const order=optionOrder(q);if(pos>=0&&pos<order.length)choose(q,order[pos])}

function showFeedback(q,ans){const f=$('#feedback');if(!ans?.selected){f.className='feedback';f.innerHTML='<div class="pre-solution-note">Chọn một đáp án để mở lời giải tĩnh đã lưu sẵn cho chính câu này.</div>';return}const correct=ans.selected===q.correct_option_id,order=optionOrder(q),pos=order.indexOf(q.correct_option_id),text=q.options.find(o=>o.id===q.correct_option_id).text,solution=SOLUTIONS[q.id];if(!solution)throw new Error(`Không có lời giải tĩnh cho ${q.id}`);f.className='feedback show '+(correct?'ok':'bad');f.innerHTML=`<h3>${correct?'✅ Chính xác':'❌ Chưa đúng'}</h3><div class="answer-line"><b>Đáp án:</b> ${letters[pos]}. ${escapeHtml(text)}</div>${solutionHtml(q,solution,order)}`}
function solutionHtml(q,s,order){const calc=s.calculation?`<section class="solution-section calculation"><h4>🧮 Bài giải / công thức</h4><h5>${escapeHtml(s.calculation.title)}</h5><ol>${s.calculation.steps.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol>${s.calculation.result?`<p class="calc-result"><b>Kết quả/đối chiếu:</b> ${escapeHtml(s.calculation.result)}</p>`:''}</section>`:'';const optionRows=s.options.map(x=>{const letter=letters[order.indexOf(x.id)];return `<article class="option-analysis ${x.correct?'is-correct':'is-wrong'}"><h5>${x.correct?'✅':'❌'} ${letter}. ${escapeHtml(x.text)} — ${x.correct?'Đáp án của câu':'Không chọn trong câu này'}</h5><p><b>Vì sao ${x.correct?'chọn':'không chọn'}:</b> ${escapeHtml(x.why)}</p><p><b>Khi nào phương án này đúng / dùng được:</b> ${escapeHtml(x.when)}</p></article>`}).join('');return `<div class="solution"><section class="solution-section"><h4>📘 Kiến thức nền</h4><p>${escapeHtml(s.knowledge)}</p></section><section class="solution-section"><h4>🔎 Lập luận cho câu này</h4><p>${escapeHtml(s.reasoning)}</p></section>${calc}<section class="solution-section"><h4>🧩 Phân tích tất cả phương án</h4><div class="option-analysis-list">${optionRows}</div></section><section class="solution-section"><h4>⚠️ Lỗi dễ mắc</h4><ul>${s.commonMistakes.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></section><section class="solution-section summary-box"><h4>🧠 Ghi nhớ</h4><p>${escapeHtml(s.summary)}</p></section>${q.sources?.length?`<div class="source-note">Nguồn/đối chiếu trong dữ liệu: ${q.sources.map(escapeHtml).join(', ')}</div>`:''}</div>`}

function move(d){if(!state.pool.length)return;if(state.idx===state.pool.length-1&&d>0){summary();return}const next=Math.max(0,Math.min(state.pool.length-1,state.idx+d));if(next===state.idx)return;state.idx=next;render();scrollQuestionTop()}
function jumpTo(i){if(i<0||i>=state.pool.length)return;state.idx=i;render();scrollQuestionTop()}
function renderQuestionPalette(){const box=$('#questionPalette');if(!box)return;box.innerHTML='';state.pool.forEach((q,i)=>{const ans=state.answered[q.id],b=document.createElement('button');b.type='button';b.className='q-jump';b.textContent=i+1;b.title=`Câu ${i+1} • ${q.set} • câu gốc ${q.source_number}`;if(i===state.idx)b.classList.add('current');if(ans?.selected)b.classList.add(ans.selected===q.correct_option_id?'done':'wrong');b.onclick=()=>jumpTo(i);box.appendChild(b)});requestAnimationFrame(()=>box.querySelector('.q-jump.current')?.scrollIntoView({block:'nearest',inline:'nearest'}))}
function goToNextUnanswered(){if(!state.pool.length)return;for(let step=1;step<=state.pool.length;step++){const i=(state.idx+step)%state.pool.length,q=state.pool[i];if(!state.answered[q.id]?.selected){jumpTo(i);return}}showToast('Bạn đã trả lời tất cả câu trong lượt này.')}
function updateStats(){const done=Object.values(state.answered).filter(x=>x.selected).length;$('#statTotal').textContent=state.pool.length;$('#statDone').textContent=done;$('#statScore').textContent=state.score;$('#statWrong').textContent=done-state.score;$('#progressBar').style.width=(state.pool.length?done/state.pool.length*100:0)+'%'}
function summary(){const done=Object.values(state.answered).filter(x=>x.selected).length,pct=done?Math.round(state.score/done*100):0;$('#questionCard').classList.add('hidden');$('#questionSidebar').classList.add('hidden');$('#summaryCard').classList.remove('hidden');$('#againBtn').classList.remove('hidden');$('#summaryWrongBtn').classList.remove('hidden');$('#summarySavedWrongBtn').classList.remove('hidden');$('#summaryText').innerHTML=`Bạn trả lời đúng <b>${state.score}/${done}</b> câu (${pct}%). ${done<state.pool.length?`Còn <b>${state.pool.length-done}</b> câu chưa trả lời.`:'Bạn đã hoàn thành toàn bộ câu trong lượt.'}`;scrollQuestionTop()}
function restartLastPool(){const byId=Object.fromEntries(DATA.questions.map(q=>[q.id,q])),pool=state.lastPoolIds.map(id=>byId[id]).filter(Boolean);beginPool($('#shuffleQ').checked?shuffle(pool):pool,state.mode)}
function retryWrong(){const wrong=state.pool.filter(q=>state.answered[q.id]?.selected&&state.answered[q.id].selected!==q.correct_option_id);if(!wrong.length){showToast('Chưa có câu sai trong lượt này để ôn.');return}beginPool($('#shuffleQ').checked?shuffle(wrong):wrong,'mistakes')}
function resetProgress(){if(!state.pool.length){showToast('Chưa có lượt học nào để xóa.');return}state.answered={};state.score=0;state.idx=0;$('#questionCard').classList.remove('hidden');$('#questionSidebar').classList.remove('hidden');$('#summaryCard').classList.add('hidden');render();showToast('Đã xóa kết quả của lượt hiện tại.')}

function loadMistakeBank(){try{const parsed=JSON.parse(localStorage.getItem(WRONG_STORAGE_KEY)||'{}');return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:{}}catch(e){return {}}}
function saveMistakeBank(bank){try{localStorage.setItem(WRONG_STORAGE_KEY,JSON.stringify(bank))}catch(e){}}
function recordMistake(q){const bank=loadMistakeBank(),ids=new Set(bank[q.set]||[]);ids.add(q.id);bank[q.set]=[...ids];saveMistakeBank(bank);updateMistakeBadge();renderMistakes()}
function removeMistake(id,rerender=true){const q=DATA.questions.find(x=>x.id===id);if(!q)return;const bank=loadMistakeBank(),ids=new Set(bank[q.set]||[]);if(!ids.delete(id))return;if(ids.size)bank[q.set]=[...ids];else delete bank[q.set];saveMistakeBank(bank);updateMistakeBadge();if(rerender)renderMistakes()}
function allMistakeIds(){const bank=loadMistakeBank();return [...new Set(Object.values(bank).flat())]}
function updateMistakeBadge(){const count=allMistakeIds().length;$('#mistakeTabCount').textContent=count;$('#resumeMistakesBtn').textContent=count?`Ôn câu sai đã lưu (${count})`:'Ôn câu sai đã lưu'}
function getFilteredMistakeIds(){const wanted=$('#mistakeSetFilter').value,term=$('#mistakeSearch').value.trim().toLowerCase(),ids=new Set(allMistakeIds());return DATA.questions.filter(q=>ids.has(q.id)&&(wanted==='ALL'||q.set===wanted)&&(!term||(q.question+' '+q.options.map(o=>o.text).join(' ')).toLowerCase().includes(term))).map(q=>q.id)}
function renderMistakes(){const list=$('#mistakesList');if(!list)return;const ids=getFilteredMistakeIds(),byId=Object.fromEntries(DATA.questions.map(q=>[q.id,q]));if(!ids.length){list.innerHTML='<div class="card mistake-empty"><div>✅</div><h3>Không có câu sai phù hợp</h3><p>Các câu bạn trả lời sai sẽ được lưu tại đây để làm lại sau.</p></div>';return}list.innerHTML=ids.map((id,i)=>{const q=byId[id];return `<article class="card mistake-card"><div class="mistake-number">${i+1}</div><div class="mistake-copy"><div class="mistake-meta">${escapeHtml(q.set)} • câu gốc ${q.source_number} • trang ${q.source_page}</div><h3>${escapeHtml(q.question)}</h3></div><button class="btn ghost compact mistake-review-one" data-id="${escapeHtml(q.id)}" type="button">Làm lại</button></article>`}).join('');$$('.mistake-review-one').forEach(b=>b.onclick=()=>reviewSavedMistakes([b.dataset.id]))}
function reviewSavedMistakes(ids=allMistakeIds()){const wanted=new Set(ids),pool=DATA.questions.filter(q=>wanted.has(q.id));if(!pool.length){setView('mistakes');showToast('Chưa có câu sai nào để ôn.');return}beginPool($('#shuffleQ').checked?shuffle(pool):pool,'mistakes')}
function clearMistakeBank(){if(!allMistakeIds().length){showToast('Kho câu sai đang trống.');return}if(!confirm('Xóa toàn bộ câu sai đã lưu trên trình duyệt này?'))return;saveMistakeBank({});updateMistakeBadge();renderMistakes();showToast('Đã xóa kho câu sai.')}

function setView(view,updateHash=true){if(!['study','mistakes','shortcuts'].includes(view))view='study';state.currentView=view;$$('.app-view').forEach(x=>x.classList.add('hidden'));$(`#${view}View`).classList.remove('hidden');$$('.tab-btn').forEach(b=>{const active=b.dataset.view===view;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});if(view==='mistakes')renderMistakes();if(updateHash&&location.hash!==`#${view}`)history.replaceState(null,'',`#${view}`)}
function syncViewFromHash(){const view=location.hash.replace('#','');setView(['study','mistakes','shortcuts'].includes(view)?view:'study',false)}
function toggleSetup(){const content=$('#setupContent'),btn=$('#toggleSetupBtn'),hidden=content.classList.toggle('hidden');btn.textContent=hidden?'Mở thiết lập':'Thu gọn';btn.setAttribute('aria-expanded',String(!hidden))}
function togglePalette(){const sidebar=$('#questionSidebar'),layout=document.querySelector('.quiz-layout'),btn=$('#paletteToggleBtn'),hidden=sidebar.classList.toggle('hidden');layout?.classList.toggle('palette-hidden',hidden);btn.textContent=hidden?'Hiện danh sách câu':'Ẩn danh sách câu';btn.setAttribute('aria-expanded',String(!hidden))}
function handleKeyboard(e){const tag=document.activeElement?.tagName,isTyping=['INPUT','TEXTAREA','SELECT'].includes(tag)||document.activeElement?.isContentEditable;if(e.key==='Escape'){setView('study');return}if(isTyping)return;if(e.key==='?'){e.preventDefault();setView('shortcuts');return}if(e.key.toLowerCase()==='f'){e.preventDefault();setView('study');if($('#setupContent').classList.contains('hidden'))toggleSetup();$('#searchInput').focus();return}if(state.currentView!=='study'||$('#quizArea').classList.contains('hidden')||!state.pool.length)return;if(['1','2','3','4'].includes(e.key)){e.preventDefault();chooseByPosition(Number(e.key)-1);return}if(e.key==='ArrowLeft'){e.preventDefault();move(-1);return}if(e.key==='ArrowRight'){e.preventDefault();move(1);return}if(e.key.toLowerCase()==='u'){e.preventDefault();goToNextUnanswered();return}if(e.key.toLowerCase()==='r'){e.preventDefault();retryWrong()}}
function scrollQuestionTop(){requestAnimationFrame(()=>{const el=$('#quizArea');if(el)window.scrollTo({top:Math.max(0,el.getBoundingClientRect().top+window.scrollY-12),behavior:'smooth'})})}
let toastTimer;function showToast(text){const t=$('#toast');if(!t)return;clearTimeout(toastTimer);t.textContent=text;t.classList.remove('hidden');toastTimer=setTimeout(()=>t.classList.add('hidden'),2400)}
function saveProgress(){try{const q=state.pool[state.idx];localStorage.setItem(LAST_STORAGE_KEY,JSON.stringify({set:$('#setSelect').value,question:q?.id||null,at:Date.now()}))}catch(e){}}
function escapeHtml(s){return String(s==null?'':s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.addEventListener('DOMContentLoaded',setup);
