
const DATA=window.QUIZ_DATA;
const STATIC_DATA=window.STATIC_SOLUTION_DATA;
const SOLUTIONS=STATIC_DATA?.solutions||{};
const $=s=>document.querySelector(s);
const state={pool:[],idx:0,answered:{},score:0};
const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const SOURCE_PAGE_IMAGES={1:'assets/source-page-01.png',10:'assets/source-page-10.png',19:'assets/source-page-19.png',21:'assets/source-page-21.png',49:'assets/source-page-49.png',56:'assets/source-page-56.png'};
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function validateStaticSolutions(){
  if(!STATIC_DATA||STATIC_DATA.metadata?.question_count!==DATA.metadata.question_count)throw new Error(`Thiếu dữ liệu lời giải tĩnh: cần ${DATA.metadata.question_count} câu.`);
  const missing=DATA.questions.filter(q=>!SOLUTIONS[q.id]).map(q=>q.id);
  if(missing.length)throw new Error(`Thiếu lời giải tĩnh cho ${missing.length} câu: ${missing.slice(0,10).join(', ')}`);
  for(const q of DATA.questions){const s=SOLUTIONS[q.id];if(!Array.isArray(s.options)||s.options.length!==q.options.length)throw new Error(`Lời giải tĩnh không đủ phương án: ${q.id}`)}
}
function setup(){
  try{validateStaticSolutions()}catch(e){document.body.innerHTML=`<main class="wrap"><div class="card"><h2>Không thể mở bộ đề</h2><p>${escapeHtml(e.message)}</p><p>Trang không tự sinh lời giải thay thế. Hãy sửa dữ liệu tĩnh trước khi học.</p></div></main>`;throw e}
  const set=$('#setSelect');DATA.metadata.sets.forEach(s=>set.add(new Option(`${s.name} (${s.count} câu)`,s.id)));set.add(new Option(`Tất cả (${DATA.metadata.question_count} câu)`,'ALL'),0);set.value=DATA.metadata.sets[0].id;set.onchange=buildChapters;buildChapters();$('#startBtn').onclick=start;$('#prevBtn').onclick=()=>move(-1);$('#nextBtn').onclick=()=>move(1);$('#retryWrong').onclick=retryWrong;$('#resetBtn').onclick=resetProgress;
}
function buildChapters(){const s=$('#setSelect').value,ch=$('#chapterSelect');ch.innerHTML='<option value="ALL">Tất cả chương</option>';const vals=[...new Set(DATA.questions.filter(q=>s==='ALL'||q.set===s).map(q=>q.chapter).filter(Boolean))];vals.forEach(v=>ch.add(new Option(v,v)))}
function start(){let p=DATA.questions.filter(q=>($('#setSelect').value==='ALL'||q.set===$('#setSelect').value)&&($('#chapterSelect').value==='ALL'||q.chapter===$('#chapterSelect').value));const term=$('#searchInput').value.trim().toLowerCase();if(term)p=p.filter(q=>(q.question+' '+q.options.map(o=>o.text).join(' ')).toLowerCase().includes(term));if($('#shuffleQ').checked)p=shuffle(p);state.pool=p;state.idx=0;state.answered={};state.score=0;$('#quizArea').classList.remove('hidden');render()}
function optionOrder(q){if(!state.answered[q.id]?.order){state.answered[q.id]=state.answered[q.id]||{};state.answered[q.id].order=$('#shuffleA').checked?shuffle(q.options.map(o=>o.id)):q.options.map(o=>o.id)}return state.answered[q.id].order}
function render(){const q=state.pool[state.idx];if(!q){$('#quizArea').innerHTML='<div class="card"><h2>Không tìm thấy câu hỏi phù hợp.</h2></div>';return}const ans=state.answered[q.id];$('#qPos').textContent=`Câu ${state.idx+1}/${state.pool.length}`;$('#qSource').textContent=`${q.set} • câu gốc ${q.source_number} • trang ${q.source_page}`;$('#qText').textContent=q.question;const badge=$('#statusBadge');badge.className='badge '+q.verification;badge.textContent=q.verification==='corrected'?'Đã sửa đáp án':q.verification==='warning'?'Cần lưu ý':'Đã đối chiếu';const warn=$('#warningBox');warn.textContent=q.warning||'';warn.classList.toggle('hidden',!q.warning);renderSourceImage(q);const byId=Object.fromEntries(q.options.map(o=>[o.id,o]));const box=$('#options');box.innerHTML='';optionOrder(q).forEach((id,i)=>{const o=byId[id],b=document.createElement('button');b.className='option';b.innerHTML=`<span class="letter">${letters[i]}</span><span>${escapeHtml(o.text)}</span>`;b.onclick=()=>choose(q,id);if(ans?.selected){b.disabled=true;if(id===q.correct_option_id)b.classList.add('correct');if(id===ans.selected&&id!==q.correct_option_id)b.classList.add('wrong')}box.appendChild(b)});showFeedback(q,ans);updateStats();$('#prevBtn').disabled=state.idx===0;$('#nextBtn').textContent=state.idx===state.pool.length-1?'Kết thúc':'Câu tiếp'}
function sourceImageFor(q){if(q.image)return q.image;const dependsOnVisual=/hình|sơ đồ|cửa sổ|diagram|figure/i.test(q.warning||'');return dependsOnVisual?SOURCE_PAGE_IMAGES[q.source_page]||null:null}
function renderSourceImage(q){const wrap=$('#sourceImageWrap'),img=$('#sourceImage'),link=$('#sourceImageLink'),src=sourceImageFor(q);if(src){img.src=src;img.alt=`Ảnh/trang đề gốc - ${q.set}, câu ${q.source_number}, trang ${q.source_page}`;link.href=src;wrap.classList.remove('hidden')}else{wrap.classList.add('hidden');img.removeAttribute('src');link.removeAttribute('href')}}
function choose(q,id){if(state.answered[q.id]?.selected)return;state.answered[q.id].selected=id;if(id===q.correct_option_id)state.score++;render();saveProgress()}
function showFeedback(q,ans){const f=$('#feedback');if(!ans?.selected){f.className='feedback';f.innerHTML='<div class="pre-solution-note">Chọn một đáp án để mở lời giải tĩnh đã lưu sẵn cho chính câu này.</div>';return}const correct=ans.selected===q.correct_option_id;const order=optionOrder(q),pos=order.indexOf(q.correct_option_id);const text=q.options.find(o=>o.id===q.correct_option_id).text;const solution=SOLUTIONS[q.id];if(!solution)throw new Error(`Không có lời giải tĩnh cho ${q.id}`);f.className='feedback show '+(correct?'ok':'bad');f.innerHTML=`<h3>${correct?'✅ Chính xác':'❌ Chưa đúng'}</h3><div class="answer-line"><b>Đáp án:</b> ${letters[pos]}. ${escapeHtml(text)}</div>${solutionHtml(q,solution,order)}`}
function solutionHtml(q,s,order){const calc=s.calculation?`<section class="solution-section calculation"><h4>🧮 Bài giải / công thức</h4><h5>${escapeHtml(s.calculation.title)}</h5><ol>${s.calculation.steps.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol>${s.calculation.result?`<p class="calc-result"><b>Kết quả/đối chiếu:</b> ${escapeHtml(s.calculation.result)}</p>`:''}</section>`:'';const optionRows=s.options.map(x=>{const letter=letters[order.indexOf(x.id)];return `<article class="option-analysis ${x.correct?'is-correct':'is-wrong'}"><h5>${x.correct?'✅':'❌'} ${letter}. ${escapeHtml(x.text)} — ${x.correct?'Đáp án của câu':'Không chọn trong câu này'}</h5><p><b>Vì sao ${x.correct?'chọn':'không chọn'}:</b> ${escapeHtml(x.why)}</p><p><b>Khi nào phương án này đúng / dùng được:</b> ${escapeHtml(x.when)}</p></article>`}).join('');return `<div class="solution"><section class="solution-section"><h4>📘 Kiến thức nền</h4><p>${escapeHtml(s.knowledge)}</p></section><section class="solution-section"><h4>🔎 Lập luận cho câu này</h4><p>${escapeHtml(s.reasoning)}</p></section>${calc}<section class="solution-section"><h4>🧩 Phân tích tất cả phương án</h4><div class="option-analysis-list">${optionRows}</div></section><section class="solution-section"><h4>⚠️ Lỗi dễ mắc</h4><ul>${s.commonMistakes.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></section><section class="solution-section summary-box"><h4>🧠 Ghi nhớ</h4><p>${escapeHtml(s.summary)}</p></section>${q.sources?.length?`<div class="source-note">Nguồn/đối chiếu trong dữ liệu: ${q.sources.map(escapeHtml).join(', ')}</div>`:''}</div>`}
function move(d){if(state.idx===state.pool.length-1&&d>0){summary();return}state.idx=Math.max(0,Math.min(state.pool.length-1,state.idx+d));render();window.scrollTo({top:0,behavior:'smooth'})}
function updateStats(){const done=Object.values(state.answered).filter(x=>x.selected).length;$('#statTotal').textContent=state.pool.length;$('#statDone').textContent=done;$('#statScore').textContent=state.score;$('#statWrong').textContent=done-state.score;$('#progressBar').style.width=(state.pool.length?done/state.pool.length*100:0)+'%'}
function summary(){const done=Object.values(state.answered).filter(x=>x.selected).length;const pct=done?Math.round(state.score/done*100):0;$('#quizArea').innerHTML=`<div class="card"><h2>Hoàn thành lượt học</h2><p>Bạn trả lời đúng <b>${state.score}/${done}</b> câu (${pct}%).</p><button id="again" class="btn primary">Làm lại bộ này</button> <button id="wrongOnly" class="btn ghost">Ôn câu sai</button></div>`;$('#again').onclick=start;$('#wrongOnly').onclick=retryWrong}
function retryWrong(){const wrong=state.pool.filter(q=>state.answered[q.id]?.selected&&state.answered[q.id].selected!==q.correct_option_id);if(!wrong.length){alert('Chưa có câu sai để ôn.');return}state.pool=$('#shuffleQ').checked?shuffle(wrong):wrong;state.idx=0;state.answered={};state.score=0;$('#quizArea').classList.remove('hidden');render()}
function saveProgress(){try{localStorage.setItem('networkQuizLast',JSON.stringify({set:$('#setSelect').value,at:Date.now()}))}catch(e){}}
function resetProgress(){state.answered={};state.score=0;render()}
function escapeHtml(s){return String(s==null?'':s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.addEventListener('DOMContentLoaded',setup);
