(function(){
'use strict';
const GROUPS=[
{id:'tcp',icon:'🔁',title:'TCP: SEQ / ACK / cửa sổ',about:'Theo dõi số thứ tự hai chiều, ACK kế tiếp, SYN/FIN và cửa sổ truyền.',formulas:['ACK = SEQ + số byte dữ liệu đã nhận liên tục','SYN hoặc FIN tiêu thụ 1 sequence number ⇒ ACK = SEQ + 1','Luôn tách riêng không gian SEQ của A→B và B→A.'],re:/\b(tcp|seq|ack|sequence|rwnd|cwnd)\b|bắt tay|cửa sổ|window/i},
{id:'ipv4',icon:'🌐',title:'IPv4 / Subnet / CIDR',about:'Tính subnet mask, số host, network/broadcast, bước nhảy và chia mạng con.',formulas:['h = 32 − prefix','Tổng địa chỉ = 2^h; host dùng được thường = 2^h − 2','Bước nhảy = 256 − giá trị mask ở octet đang chia.'],re:/ipv4|subnet|cidr|subnet mask|địa chỉ mạng|network address|broadcast|số host|prefix|\/\d{1,2}\b/i},
{id:'delay',icon:'⏱️',title:'Thời gian truyền / độ trễ / thông lượng',about:'Đổi đơn vị và tính transmission delay, propagation delay, thời gian đầu-cuối hoặc tốc độ truyền.',formulas:['t_truyền = L / R','t_lan_truyền = d / v','Độ trễ tổng ≈ xử lý + hàng đợi + truyền + lan truyền.'],re:/độ trễ|delay|thời gian|truyền.*(bit|byte|gói|packet)|tốc độ truyền|throughput|bps|kbps|mbps|gbps|giây|\bms\b/i},
{id:'signal',icon:'📶',title:'Tín hiệu / Nyquist / Shannon / băng thông',about:'Các bài tốc độ dữ liệu, mức tín hiệu, SNR, băng thông và dung lượng kênh.',formulas:['Nyquist: C = 2B·log₂(M)','Shannon: C = B·log₂(1 + S/N)','SNR(dB) = 10·log₁₀(S/N).'],re:/nyquist|shannon|snr|baud|tín hiệu|signal|băng thông|bandwidth|tần số|qam|psk|fsk|pcm/i},
{id:'error',icon:'🧮',title:'CRC / Checksum / phát hiện lỗi',about:'Chia modulo-2, tạo CRC, checksum bù 1, parity và các bước kiểm tra lỗi.',formulas:['CRC: nối r bit 0, chia modulo-2 cho đa thức sinh, lấy phần dư r bit','Checksum: cộng các từ theo bù 1 rồi đảo bit kết quả','Modulo-2: phép trừ chính là XOR, không mượn.'],re:/\bcrc\b|checksum|parity|hamming|đa thức|phát hiện lỗi|kiểm tra lỗi/i},
{id:'mac',icon:'🖧',title:'Ethernet / MAC / CSMA / ARQ',about:'Các bài va chạm, kích thước frame, hiệu suất truy nhập và truyền tin cậy ở liên kết.',formulas:['Frame tối thiểu phải phát đủ lâu để phát hiện va chạm vòng đi-về','Stop-and-Wait: xét thời gian truyền frame + propagation + ACK','Luôn đổi frame về bit và tốc độ về bit/s trước khi tính.'],re:/ethernet|csma|aloha|collision|va chạm|đụng độ|frame|khung|stop-and-wait|go-back-n|selective repeat|\barq\b/i},
{id:'other',icon:'🧭',title:'Định tuyến & bài tính tổng hợp khác',about:'Các bài số học mạng còn lại: chi phí đường đi, metric, chuyển đổi đơn vị hoặc công thức đặc thù.',formulas:['Viết rõ dữ kiện và đơn vị trước khi thế số','Nếu là đường đi: tổng cost = tổng trọng số các cạnh','Kiểm tra đáp án bằng thứ nguyên và cỡ lớn kết quả.'],re:/dijkstra|routing|định tuyến|đường đi|metric|cost|hop|distance vector|link state/i}
];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=v=>String(v??'').normalize('NFC').replace(/\s+/g,' ').trim();
function getSolutions(){return window.MANUAL_SOLUTIONS||window.STATIC_SOLUTION_DATA?.solutions||window.SOLUTIONS||{};}
function getQuestions(){return Array.isArray(window.QUIZ_DATA?.questions)?window.QUIZ_DATA.questions:[];}
function correctText(q){return q?.options?.find(o=>o.id===q.correct_option_id)?.text||'';}
function classify(q,s){const hay=norm([q?.question,s?.calculation?.title,(s?.calculation?.steps||[]).join(' '),s?.knowledge].join(' '));for(const g of GROUPS.slice(0,-1))if(g.re.test(hay))return g.id;return 'other';}
function collectExercises(){const sol=getSolutions(),byId=new Map(getQuestions().map(q=>[q.id,q])),out=[];for(const [id,s] of Object.entries(sol||{})){if(!s?.calculation||!Array.isArray(s.calculation.steps)||!s.calculation.steps.length)continue;const q=byId.get(id);if(q)out.push({id,q,s,group:classify(q,s)});}out.sort((a,b)=>String(a.q.set).localeCompare(String(b.q.set),'vi')||Number(a.q.source_number||0)-Number(b.q.source_number||0));return out;}
function injectShell(){if(document.getElementById('tabPractice'))return;const nav=document.querySelector('#appTabs .tabs-inner'),main=document.querySelector('main.page-wrap,main.wrap,main');if(!nav||!main)return;const tab=document.createElement('button');tab.id='tabPractice';tab.className='app-tab';tab.type='button';tab.setAttribute('role','tab');tab.setAttribute('aria-selected','false');tab.setAttribute('aria-controls','practiceTabPanel');tab.innerHTML='<span class="tab-icon">🧠</span><span>Học theo dạng bài</span><span id="practiceTabBadge" class="tab-count"></span>';nav.appendChild(tab);const panel=document.createElement('section');panel.id='practiceTabPanel';panel.className='tab-panel hidden';panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby','tabPractice');panel.innerHTML='<section class="panel practice-panel"><div class="practice-loading">Đang gom các bài tập theo dạng…</div></section>';main.appendChild(panel);tab.addEventListener('click',showPractice);document.getElementById('tabStudy')?.addEventListener('click',hidePractice);document.getElementById('tabWrong')?.addEventListener('click',hidePractice);}
function hidePractice(){const p=document.getElementById('practiceTabPanel'),t=document.getElementById('tabPractice');p?.classList.add('hidden');t?.classList.remove('active');t?.setAttribute('aria-selected','false');}
function showPractice(){const p=document.getElementById('practiceTabPanel');if(!p)return;document.getElementById('studyTabPanel')?.classList.add('hidden');document.getElementById('wrongTabPanel')?.classList.add('hidden');for(const id of ['tabStudy','tabWrong']){const t=document.getElementById(id);t?.classList.remove('active');t?.setAttribute('aria-selected','false');}p.classList.remove('hidden');const t=document.getElementById('tabPractice');t?.classList.add('active');t?.setAttribute('aria-selected','true');document.body.classList.remove('learning-active');requestAnimationFrame(()=>p.scrollIntoView({behavior:'smooth',block:'start'}));}
function exerciseHtml(item,index){const {q,s}=item,c=s.calculation,steps=(c.steps||[]).map((x,i)=>`<li><b>Bước ${i+1}:</b> ${esc(x)}</li>`).join(''),mistakes=(s.commonMistakes||[]).slice(0,4).map(x=>`<li>${esc(x)}</li>`).join('');return `<details class="practice-exercise"><summary><span class="practice-qno">${index+1}</span><span><b>${esc(q.set)} · Câu ${esc(q.source_number)}</b><small>${esc(q.question)}</small></span></summary><div class="practice-exercise-body"><div class="practice-question"><b>Đề:</b> ${esc(q.question)}</div><div class="practice-calc"><h5>🧩 ${esc(c.title||'Sườn giải từng bước')}</h5><ol>${steps}</ol>${c.result?`<p class="practice-result"><b>Kết quả:</b> ${esc(c.result)}</p>`:''}</div><div class="practice-answer"><b>Đáp án đúng:</b> ${esc(correctText(q))}</div><details class="practice-more"><summary>Xem giải thích đầy đủ của câu</summary><div><p><b>Kiến thức cần nhớ:</b> ${esc(s.knowledge||'')}</p><p><b>Vì sao chọn:</b> ${esc(s.reasoning||'')}</p>${mistakes?`<p><b>Lỗi dễ mắc:</b></p><ul>${mistakes}</ul>`:''}</div></details></div></details>`;}
function groupHtml(g,items){return `<article class="practice-group" id="practice-group-${g.id}"><div class="practice-group-head"><div class="practice-group-icon">${g.icon}</div><div><span class="practice-eyebrow">DẠNG ${GROUPS.indexOf(g)+1}</span><h3>${esc(g.title)}</h3><p>${esc(g.about)}</p></div><strong>${items.length} bài</strong></div><div class="practice-formula"><h4>📌 Công thức / quy trình chung</h4><ul>${g.formulas.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="practice-actions"><button class="btn ghost practice-expand" type="button" data-target="${g.id}">Mở toàn bộ bài dạng này</button><span>Học sườn chung trước, sau đó mở từng bài để xem cách thế số.</span></div><div class="practice-exercises">${items.map((x,i)=>exerciseHtml(x,i)).join('')||'<p class="practice-empty">Chưa có bài được gắn vào dạng này.</p>'}</div></article>`;}
function render(){injectShell();const host=document.querySelector('#practiceTabPanel .practice-panel');if(!host)return;const exercises=collectExercises(),grouped=Object.fromEntries(GROUPS.map(g=>[g.id,[]]));for(const x of exercises)grouped[x.group].push(x);const badge=document.getElementById('practiceTabBadge');if(badge)badge.textContent=String(exercises.length);host.innerHTML=`<div class="practice-hero"><div><span class="eyebrow">HỌC BÀI TẬP THEO DẠNG</span><h2>Nhìn dạng → chọn công thức → thế số → kiểm tra kết quả</h2><p>Hệ thống tự gom mọi câu có phần tính toán chi tiết trong bộ 314 câu vào 7 dạng. Mỗi dạng có sườn chung và toàn bộ lời giải từng bước của các câu thuộc dạng đó.</p></div><div class="practice-total"><b>${exercises.length}</b><span>bài tập</span><small>7 dạng</small></div></div><div class="practice-jump">${GROUPS.map((g,i)=>`<a href="#practice-group-${g.id}">${i+1}. ${esc(g.title)} <b>${grouped[g.id].length}</b></a>`).join('')}</div><div class="practice-groups">${GROUPS.map(g=>groupHtml(g,grouped[g.id])).join('')}</div>`;host.querySelectorAll('.practice-expand').forEach(btn=>btn.addEventListener('click',()=>{const box=document.querySelector(`#practice-group-${btn.dataset.target}`),ds=[...(box?.querySelectorAll('.practice-exercise')||[])],open=ds.some(d=>!d.open);ds.forEach(d=>d.open=open);btn.textContent=open?'Thu gọn toàn bộ':'Mở toàn bộ bài dạng này';}));window.MMT_PRACTICE_BY_TYPE=Object.freeze({exerciseCount:exercises.length,groupCounts:Object.fromEntries(GROUPS.map(g=>[g.id,grouped[g.id].length]))});}
function boot(){if(!document.getElementById('practiceByTypeCss')){const l=document.createElement('link');l.id='practiceByTypeCss';l.rel='stylesheet';l.href='practice_by_type.css?v=20260809-1';document.head.appendChild(l);}injectShell();let n=0;const timer=setInterval(()=>{n++;if(getQuestions().length&&Object.keys(getSolutions()).length){clearInterval(timer);render();}else if(n>40){clearInterval(timer);render();}},50);}
boot();
})();
