window.MANUAL_SOLUTIONS=Object.assign(window.MANUAL_SOLUTIONS||{}, {
"De01-1-0":{
knowledge:"Khi dữ liệu đi từ tầng trên xuống tầng dưới trong mô hình phân tầng, mỗi tầng thực hiện đóng gói (encapsulation): nhận PDU của tầng trên làm payload rồi bổ sung thông tin điều khiển của chính tầng đó, chủ yếu ở header và một số tầng có trailer.",
reasoning:"Câu hỏi mô tả chiều đi xuống ngăn xếp giao thức. Ở chiều này thông tin điều khiển không bị lấy ra mà được bổ sung để tầng ngang hàng ở máy nhận có thể xử lý.",
options:{a:{why:"Sai. Dữ liệu có thể được phân mảnh hoặc biến đổi ở một số giao thức, nhưng thao tác đặc trưng khi chuyển xuống tầng dưới không phải 'sắp lại' payload mà là đóng gói.",when:"Chỉ hợp lý nếu một câu hỏi riêng nói về cơ chế sắp xếp lại dữ liệu/segment theo số thứ tự ở bên nhận, không phải quá trình đóng gói OSI."},b:{why:"Đúng. Tầng dưới thêm header của nó vào PDU nhận từ tầng trên; ví dụ Transport thêm TCP header, Network thêm IP header, Data Link thêm frame header/trailer.",when:"Đúng khi dữ liệu đi từ tầng cao xuống tầng thấp ở phía gửi (encapsulation)."},c:{why:"Sai trong câu này. Một tầng có thể cập nhật một số trường header do chính nó quản lý, nhưng khái niệm tổng quát được hỏi là thêm thông tin điều khiển mới của tầng.",when:"Có thể đúng khi đề hỏi việc router/host cập nhật một trường đã tồn tại, chẳng hạn TTL, checksum hoặc cờ/trường trạng thái."},d:{why:"Sai. Bớt header là thao tác decapsulation ở chiều nhận khi dữ liệu đi từ tầng thấp lên tầng cao.",when:"Đúng khi PDU đi lên ngăn xếp ở máy nhận và mỗi tầng gỡ header/trailer của chính mình."}},
commonMistakes:["Nhầm chiều encapsulation với decapsulation."],summary:"Đi xuống: thêm header/trailer; đi lên: kiểm tra rồi gỡ thông tin điều khiển của tầng."},
"De01-2-1":{
knowledge:"OSI có 7 tầng: Physical(1), Data Link(2), Network(3), Transport(4), Session(5), Presentation(6), Application(7). 'Cấp mạng/tầng mạng' tương ứng Network Layer.",
reasoning:"Từ khóa 'cấp mạng' chỉ trực tiếp tầng Network, tầng 3, nơi xử lý địa chỉ logic và định tuyến packet.",
options:{a:{why:"Sai. Physical là tầng 1, chịu trách nhiệm biểu diễn và truyền bit trên môi trường vật lý; không thực hiện định tuyến mạng.",when:"Đúng nếu câu hỏi hỏi tầng truyền bit, tín hiệu điện/quang, đầu nối hoặc tốc độ bit."},b:{why:"Sai. Data Link là tầng 2, xử lý frame, MAC và truyền trên một liên kết cục bộ.",when:"Đúng nếu câu hỏi hỏi frame, địa chỉ MAC, Ethernet switching/bridge hoặc truy nhập môi trường."},c:{why:"Sai. Application là tầng 7, cung cấp dịch vụ mạng cho ứng dụng như HTTP, DNS, SMTP.",when:"Đúng nếu đề hỏi tầng gần ứng dụng người dùng hoặc các giao thức ứng dụng."},d:{why:"Đúng. Network là tầng 3, vận chuyển packet qua liên mạng, dùng địa chỉ logic và chọn đường.",when:"Đúng khi đề nói về IP, router, packet, định tuyến hoặc địa chỉ logic lớp 3."}},
commonMistakes:["Học vị trí tầng không theo thứ tự 1→7."],summary:"Network = OSI layer 3."},
"De01-4-3":{
knowledge:"Trong môi trường truy nhập ngẫu nhiên dùng chung, va chạm xuất hiện khi từ hai trạm trở lên truyền chồng lấn trên cùng miền va chạm. Nếu chỉ một trạm truyền còn các trạm khác nhận/im lặng thì không có va chạm do tranh chấp.",
reasoning:"Đề hỏi trường hợp KHÔNG xảy ra đụng độ. Chỉ phương án c mô tả đúng tình huống có một trạm phát duy nhất.",
options:{a:{why:"Sai vì phương án nói một trạm truyền và các trạm khác cũng cùng truyền; có nhiều máy phát đồng thời nên chính là điều kiện dễ gây collision.",when:"Mô tả này đúng nếu câu hỏi hỏi tình huống có khả năng xảy ra đụng độ trên kênh chia sẻ."},b:{why:"Sai. Hai trạm cùng phát trên cùng môi trường chia sẻ có thể làm tín hiệu chồng lấn và va chạm.",when:"Đúng nếu đề hỏi một ví dụ tối thiểu về collision: chỉ cần hai trạm phát đồng thời là đủ."},c:{why:"Đúng. Một trạm phát còn tất cả trạm khác chỉ nhận nên không có hai tín hiệu phát cạnh tranh cùng lúc.",when:"Đúng khi xét một collision domain/kênh dùng chung và chỉ có một transmitter hoạt động tại thời điểm đó."},d:{why:"Sai. Vị trí 'đầu' hay 'cuối' không loại bỏ va chạm; nếu cả hai cùng truyền trên cùng miền va chạm thì vẫn có thể collision.",when:"Chỉ có thể không va chạm nếu hai đầu nằm ở các miền va chạm tách biệt, nhưng đó không phải giả thiết của câu."}},
commonMistakes:["Cho rằng trạm ở xa nhau thì không va chạm."],summary:"Kênh chia sẻ tránh collision tại một thời điểm khi chỉ một trạm phát."},
"De01-5-4":{
knowledge:"Trong TCP, ACK biểu diễn số thứ tự byte kế tiếp mà bên nhận mong đợi. SYN chiếm một số thứ tự, nên xác nhận SYN có dạng ACK = SEQ + 1.",
reasoning:"Theo hình nguồn, A gửi với Seq=5 nên B phải xác nhận 6; B gửi với Seq=7 nên A phải xác nhận 8. Vì vậy A1=6, A2=8.",
options:{a:{why:"Sai. 3 và 5 không thu được từ quy tắc ACK=SEQ+1 với các Seq 5 và 7 trong hình.",when:"Cặp 3,5 chỉ đúng nếu hai số thứ tự cần xác nhận lần lượt là 2 và 4 (và mỗi segment tiêu thụ một số thứ tự như SYN)."},b:{why:"Sai. 7,9 tương ứng việc xác nhận Seq 6 và 8, không khớp các Seq đang thể hiện trong sơ đồ.",when:"Đúng nếu sơ đồ cho hai Seq cần ACK lần lượt bằng 6 và 8."},c:{why:"Sai. 4,6 tương ứng Seq 3 và 5; chỉ giá trị 6 có thể liên hệ Seq=5, còn 4 không khớp chiều còn lại.",when:"Đúng nếu các Seq cần xác nhận lần lượt là 3 và 5."},d:{why:"Đúng. B xác nhận Seq=5 bằng ACK=6; A xác nhận Seq=7 bằng ACK=8, nên A1=6 và A2=8.",when:"Đúng với chính sơ đồ nguồn khi các segment/SYN đang xét làm số ACK tiến thêm 1."}},
calculation:{title:"Tính ACK trong bắt tay TCP",steps:["Đọc Seq của chiều A→B: 5.","ACK mà B gửi về = 5 + 1 = 6 ⇒ A1=6.","Đọc Seq của chiều B→A: 7.","ACK mà A gửi về = 7 + 1 = 8 ⇒ A2=8."],result:"A1=6, A2=8."},
commonMistakes:["Cộng nhầm ACK vào chính ACK cũ thay vì Seq của chiều đối diện.","Quên SYN tiêu thụ một sequence number."],summary:"TCP ACK = số thứ tự kế tiếp mong đợi; trong hình: 5→6 và 7→8."},
"De01-6-5":{
knowledge:"Protocol là tập quy tắc quy định cách các thực thể ngang hàng giao tiếp: định dạng/thứ tự thông điệp, ý nghĩa trường dữ liệu và hành động khi gửi/nhận. Service mô tả cái tầng cung cấp cho tầng trên; interface mô tả cách truy cập service.",
reasoning:"Phương án b mô tả đúng bản chất giao thức: cách hai thành phần giao tiếp trao đổi thông tin với nhau.",
options:{a:{why:"Sai. 'Cách sử dụng dịch vụ' gần với giao diện/service primitives hơn là định nghĩa protocol giữa hai peer.",when:"Đúng nếu câu hỏi hỏi interface hoặc cách tầng trên gọi các primitive để sử dụng dịch vụ tầng dưới."},b:{why:"Đúng. Giao thức quy định quy tắc trao đổi giữa các thực thể giao tiếp cùng mức.",when:"Đúng khi hỏi định nghĩa protocol trong kiến trúc mạng."},c:{why:"Sai. Nội dung máy chủ cung cấp cho khách hàng mô tả service/chức năng dịch vụ, không phải protocol.",when:"Đúng nếu hỏi 'dịch vụ là gì' trong mô hình client-server hoặc phân tầng."},d:{why:"Sai. Cách truy cập một dịch vụ là khía cạnh interface/API, không phải quy tắc trao đổi ngang hàng.",when:"Đúng nếu đề hỏi giao diện dịch vụ hoặc service access point/primitive."}},commonMistakes:["Nhầm protocol với service và interface."],summary:"Protocol = quy tắc peer-to-peer; Service = cái được cung cấp; Interface = cách truy cập service."},
"De01-7-6":{
knowledge:"Tín hiệu analog biến thiên liên tục theo thời gian/biên độ; tín hiệu digital có các mức rời rạc. 'Quang' và 'cáp đồng' là môi trường/phương tiện hoặc dạng vật lý, không phải phân loại liên tục-rời rạc được hỏi.",
reasoning:"Cụm 'tín hiệu điện tử liên tục' là định nghĩa của tín hiệu tương tự (analog).",
options:{a:{why:"Sai. Tín hiệu quang nói về cách mang năng lượng bằng ánh sáng; tín hiệu quang vẫn có thể được điều chế theo nhiều cách và không đồng nghĩa với 'liên tục' theo định nghĩa analog.",when:"Đúng nếu đề hỏi loại tín hiệu truyền trong sợi quang hoặc môi trường dùng ánh sáng."},b:{why:"Sai. 'Cáp đồng' là môi trường truyền dẫn, không phải loại tín hiệu theo tính liên tục/rời rạc.",when:"Đúng nếu hỏi môi trường vật lý thường mang tín hiệu điện."},c:{why:"Đúng. Analog là tín hiệu có đại lượng biến thiên liên tục.",when:"Đúng khi mô tả tín hiệu liên tục theo thời gian hoặc biên độ."},d:{why:"Sai. Digital biểu diễn bằng các mức rời rạc, điển hình 0/1, trái với từ 'liên tục'.",when:"Đúng nếu đề nói tín hiệu có các mức rời rạc/bit."}},commonMistakes:["Nhầm phương tiện truyền với loại tín hiệu."],summary:"Liên tục ⇒ analog; rời rạc ⇒ digital."},
"De01-8-7":{
knowledge:"DNS dùng các resource record khác nhau: A/AAAA ánh xạ tên sang IP, NS chỉ name server có thẩm quyền, MX chỉ mail exchanger nhận thư cho domain, CNAME tạo bí danh.",
reasoning:"MX là viết tắt của Mail Exchanger nên phương án c đúng.",
options:{a:{why:"Sai. Địa chỉ IPv4 tương ứng tên miền do bản ghi A cung cấp (IPv6 là AAAA), không phải MX.",when:"Đúng nếu câu hỏi hỏi chức năng A/AAAA record."},b:{why:"Sai. Name server của miền được chỉ ra bởi NS record.",when:"Đúng nếu câu hỏi hỏi NS record."},c:{why:"Đúng. MX record chỉ máy chủ nhận email cho domain và thường kèm giá trị preference/priority.",when:"Đúng khi hỏi mail exchanger của miền."},d:{why:"Sai. Bí danh của một canonical name do CNAME record biểu diễn.",when:"Đúng nếu câu hỏi hỏi CNAME."}},commonMistakes:["Nhầm MX, NS, A và CNAME vì đều chứa tên miền."],summary:"A→IP, NS→name server, MX→mail server, CNAME→alias."},
"De01-9-8":{
knowledge:"Truyền tin cậy/thứ tự thường cần phối hợp sequence number, acknowledgement và timer/timeout: sequence để phát hiện mất/trùng và sắp thứ tự, ACK xác nhận, timeout kích hoạt truyền lại khi ACK/dữ liệu mất.",
reasoning:"Không một cơ chế đơn lẻ trong A/B/C đủ bao quát cả giao hàng tin cậy và đúng thứ tự; vì vậy chọn 'tất cả các phương pháp trên'.",
options:{a:{why:"Đúng là một thành phần cần thiết: timer/timeout phát hiện việc chờ ACK quá lâu để truyền lại, nhưng tự timer không xác định thứ tự frame hay xác nhận frame nào đã đến.",when:"Đúng nếu câu hỏi riêng hỏi cơ chế phát hiện gián tiếp mất gói/ACK và kích hoạt retransmission."},b:{why:"ACK cho biết dữ liệu/frame đã được nhận, nhưng một mình ACK không đủ chống trùng và bảo đảm thứ tự nếu không có số thứ tự.",when:"Đúng nếu câu hỏi hỏi cơ chế báo nhận."},c:{why:"Sequence number cho phép nhận biết thứ tự, mất và trùng frame, nhưng một mình số thứ tự không tạo phản hồi hay quyết định khi nào truyền lại.",when:"Đúng nếu hỏi cách đánh dấu thứ tự/nhận diện frame."},d:{why:"Đúng. Phối hợp sequence number + ACK + timeout tạo cơ chế ARQ tin cậy và giữ thứ tự.",when:"Đúng khi yêu cầu đồng thời giao hàng tin cậy, phát hiện mất/trùng và duy trì đúng thứ tự."}},commonMistakes:["Chọn ACK và bỏ qua vai trò của sequence/timeout."],summary:"Reliable ordered delivery = sequence + ACK + timeout/retransmission."},
"De01-10-9":{
knowledge:"Mạng lớp C theo classful có prefix mặc định /24. Mượn 5 bit từ 8 bit host làm subnet ⇒ prefix mới /29. Octet cuối /29 là 11111000₂ = 248.",
reasoning:"Subnet mask cần 29 bit 1 liên tiếp: 255.255.255.248.",
options:{a:{why:"Đúng. /29 có octet cuối 11111000₂=248 nên mask là 255.255.255.248.",when:"Đúng cho prefix /29, hay lớp C /24 mượn 5 bit host."},b:{why:"Sai. 255.255.255.128 là /25, chỉ mượn 1 bit từ host của lớp C.",when:"Đúng nếu lớp C /24 chỉ mượn 1 bit subnet."},c:{why:"Sai. 255.255.224.0 là /19, không thể là kết quả của việc từ /24 mượn thêm bit; nó còn ngắn hơn /24.",when:"Đúng nếu prefix cần dùng là /19 trong một bài khác."},d:{why:"Sai. Subnet mask hợp lệ phải có các bit 1 liên tục rồi các bit 0 liên tục; 255.255.255.1 có octet 00000001 nên không phải mask CIDR thông thường.",when:"Không phải subnet mask CIDR hợp lệ; giá trị 1 có thể xuất hiện trong wildcard/bitmask khác nhưng không theo nghĩa subnet mask này."}},
calculation:{title:"Tính subnet mask",steps:["Lớp C mặc định: /24.","Mượn 5 bit host: 24+5=29 ⇒ /29.","Octet cuối có 5 bit 1: 11111000₂.","128+64+32+16+8=248."],result:"255.255.255.248 (/29)."},commonMistakes:["Mượn bit nhưng không cộng vào prefix ban đầu."],summary:"/24 + 5 bit = /29 = 255.255.255.248."},
"De01-11-10":{
knowledge:"Circuit switching thiết lập một đường/kênh logic trước khi truyền và dành trước tài nguyên (ví dụ time slot/frequency band). Vì tài nguyên được đặt trước, lưu lượng đã được admission/thiết lập nên không có cơ chế congestion control theo kiểu packet-switched best-effort trong quá trình truyền như phát biểu của đề.",
reasoning:"Đề hỏi phát biểu KHÔNG đúng. 'Cần cơ chế điều khiển tắc nghẽn' là phát biểu không đặc trưng cho mạng chuyển mạch kênh sau khi kênh đã được cấp.",
options:{a:{why:"Đúng về circuit switching: tài nguyên dành trước giúp cung cấp băng thông/độ trễ ổn định và hỗ trợ QoS dự đoán được.",when:"Đúng khi kênh được thiết lập và tài nguyên được dành riêng."},b:{why:"Đây là lựa chọn KHÔNG đúng cần chọn. Circuit switching giải quyết tranh chấp tài nguyên chủ yếu ở giai đoạn thiết lập/admission; một cuộc gọi đã được cấp kênh không phải cạnh tranh từng packet như packet switching.",when:"'Cần congestion control' đúng hơn khi nói về mạng chuyển gói chia sẻ tài nguyên, nơi tải có thể vượt khả năng phục vụ của router/link."},c:{why:"Đúng. FDM và TDM là hai cách cổ điển chia tài nguyên vật lý thành các kênh cho circuit switching.",when:"Đúng khi hệ thống tạo kênh riêng bằng dải tần hoặc khe thời gian."},d:{why:"Đúng. Phải thiết lập circuit trước rồi mới truyền dữ liệu qua tài nguyên đã dành.",when:"Đúng với mạng chuyển mạch kênh có pha connection setup."}},commonMistakes:["Đọc sót chữ KHÔNG ĐÚNG."],summary:"Circuit switching: setup trước, reserve tài nguyên; congestion kiểu packet network không phải đặc trưng trong phiên đã cấp kênh."},
"De01-12-11":{
knowledge:"CSMA/CD gồm Carrier Sense + Multiple Access + Collision Detection. Trạm nghe trước khi truyền, nhưng để phát hiện collision nó phải tiếp tục giám sát môi trường trong khi đang phát và so sánh/nhận biết tín hiệu bất thường.",
reasoning:"Câu hỏi hỏi riêng cách phát hiện collision, nên thao tác quyết định là vừa truyền vừa tiếp tục thăm dò đường truyền.",
options:{a:{why:"Sai vì trộn 'cửa sổ trượt' vào phát hiện collision. Sliding window là cơ chế điều khiển luồng/ARQ, không phải cơ chế Ethernet collision detection.",when:"Phần 'lắng nghe đường truyền' đúng trong carrier sensing; cửa sổ trượt chỉ đúng khi hỏi truyền tin cậy/flow control."},b:{why:"Đúng. Trong Ethernet half-duplex CSMA/CD, thiết bị vừa phát vừa theo dõi môi trường để phát hiện va chạm.",when:"Đúng khi hỏi bước Collision Detection của CSMA/CD."},c:{why:"Sai. Timer có thể dùng cho backoff hoặc retransmission timing, nhưng không phải cảm biến chính phát hiện collision đang xảy ra.",when:"Timer đúng nếu hỏi thời gian chờ/backoff sau collision hoặc timeout của giao thức tin cậy."},d:{why:"Lắng nghe trước khi truyền là Carrier Sense, giúp giảm khả năng collision nhưng chưa phải cách phát hiện collision sau khi đã bắt đầu phát.",when:"Đúng nếu câu hỏi hỏi trạm làm gì trước khi truyền trong CSMA."}},commonMistakes:["Nhầm carrier sensing với collision detection."],summary:"CSMA/CD: nghe trước; khi phát vẫn tiếp tục nghe để phát hiện collision."},
"De01-13-12":{
knowledge:"Network core là phần lõi chuyển tiếp lưu lượng giữa các mạng, điển hình gồm router và các đường trục tốc độ cao. Dial-up, ADSL và LAN người dùng thuộc phía access network/edge trong cách phân chia cơ bản.",
reasoning:"Trong bốn lựa chọn, router là thành phần rõ nhất của network core.",
options:{a:{why:"Sai. Dial-up qua mạng điện thoại là một công nghệ truy nhập từ người dùng vào mạng.",when:"Đúng nếu câu hỏi hỏi ví dụ access network kiểu quay số."},b:{why:"Sai trong phân loại này. LAN thường nối end systems tới router biên nên thuộc access network/edge hơn là core.",when:"Đúng nếu hỏi mạng truy nhập tại doanh nghiệp/gia đình."},c:{why:"Đúng. Router trong lõi chuyển tiếp packet giữa các liên kết/mạng và thực hiện routing/forwarding.",when:"Đúng khi hỏi thiết bị chủ đạo của network core."},d:{why:"Sai. ADSL là công nghệ truy nhập thuê bao qua đường dây điện thoại.",when:"Đúng nếu hỏi broadband access network."}},commonMistakes:["Nhầm router biên với công nghệ đường truy nhập; dù router có thể ở edge, loại thiết bị router vẫn là phần cốt lõi của forwarding network."],summary:"Network core: routers + backbone links; ADSL/dial-up/LAN là access-side examples."},
"De01-14-13":{
knowledge:"TCP multiplex/demultiplex bằng socket endpoints. Ở máy nhận, tiến trình/dịch vụ cục bộ được xác định trực tiếp bởi địa chỉ IP đích và destination port; một kết nối TCP hoàn chỉnh được nhận dạng bởi bộ bốn {src IP, src port, dst IP, dst port}.",
reasoning:"Đề hỏi tiến trình trên máy nhận nên cặp phù hợp là IP đích + cổng đích.",
options:{a:{why:"Sai. IP nguồn + source port nhận diện endpoint bên gửi, không phải tiến trình cục bộ ở máy nhận.",when:"Đúng nếu hỏi endpoint nguồn/tiến trình gửi."},b:{why:"Đúng. Destination IP chọn giao diện/host đích, destination port dùng để demultiplex tới socket/tiến trình dịch vụ phù hợp.",when:"Đúng khi hỏi endpoint phía nhận; với kết nối cụ thể TCP còn dùng đủ 4-tuple."},c:{why:"Sai vì chỉ hai host chưa đủ phân biệt nhiều tiến trình/kết nối đồng thời giữa cùng cặp máy.",when:"Đúng nếu câu hỏi chỉ hỏi hai đầu host ở lớp mạng, không cần phân biệt process."},d:{why:"Sai. MAC chỉ dùng giao tiếp tầng 2 trên liên kết cục bộ, không định danh tiến trình TCP.",when:"Đúng nếu hỏi địa chỉ khung Ethernet/next-hop trong LAN."}},commonMistakes:["Quên port mới là khóa demultiplex tới process."],summary:"TCP process đích: destination port (gắn với IP đích); connection: 4-tuple."},
"De01-15-14":{
knowledge:"Access network nối end systems tới router biên/ISP; ví dụ LAN, ADSL, dial-up. Network core là hệ thống router và backbone chuyển tiếp giữa các mạng.",
reasoning:"Đề hỏi thành phần không thuộc access network theo phân loại giáo trình; router được xếp vào network core.",
options:{a:{why:"LAN là một dạng mạng truy nhập phổ biến đưa máy trạm tới router/gateway.",when:"Đúng nếu hỏi thành phần/access technology ở mạng cục bộ."},b:{why:"Đúng theo câu phủ định: router là thiết bị chuyển tiếp lớp 3 thuộc phần core, không phải một 'đường truy nhập' như các lựa chọn còn lại.",when:"Router là đáp án nếu hỏi thành phần core hoặc thiết bị định tuyến."},c:{why:"ADSL là công nghệ truy nhập băng rộng trên đường dây thuê bao.",when:"Đúng nếu hỏi access network DSL."},d:{why:"Dial-up qua mạng điện thoại là hình thức truy nhập người dùng cổ điển.",when:"Đúng nếu hỏi access network quay số."}},commonMistakes:["Bỏ sót chữ 'không'."],summary:"Access: LAN/ADSL/dial-up; core: router/backbone."},
"De01-16-15":{
knowledge:"Byte-oriented framing dùng byte FLAG để đánh dấu biên khung và ESC để escape dữ liệu trùng FLAG/ESC. Khi payload chứa FLAG hoặc ESC, sender chèn ESC; receiver loại ESC để phục hồi byte gốc.",
reasoning:"Phát biểu 'không cho phép truyền byte dữ liệu trùng byte cờ' là sai vì byte stuffing được thiết kế chính để cho phép điều đó.",
options:{a:{why:"Đúng: nếu payload chứa ESC, thường phải escape ESC để receiver không hiểu nhầm nó là ký tự điều khiển.",when:"Đúng với byte stuffing dùng ESC làm escape character."},b:{why:"Đúng. Byte FLAG đặc biệt đánh dấu bắt đầu/kết thúc frame trong phương pháp này.",when:"Đúng khi nói byte-oriented framing với flag delimiter."},c:{why:"Đúng. Payload trùng FLAG được chèn ESC trước để FLAG không bị hiểu là delimiter.",when:"Đúng với cơ chế character/byte stuffing."},d:{why:"Đây là phát biểu sai cần chọn. Dữ liệu hoàn toàn có thể chứa giá trị giống FLAG nhờ escaping/stuffing.",when:"Chỉ đúng trong một giao thức cực kỳ hạn chế không có cơ chế escape, nhưng không đúng phương pháp flag + byte stuffing đang hỏi."}},commonMistakes:["Nhầm 'ký tự đặc biệt không xuất hiện nguyên dạng trên dây' với 'không thể truyền giá trị đó trong dữ liệu'."],summary:"Byte stuffing cho phép payload chứa FLAG/ESC bằng cách escape chúng."},
"De01-17-16":{
knowledge:"Piggybacking trong giao tiếp song công trì hoãn ACK ngắn để gắn ACK vào frame dữ liệu đi chiều ngược, giảm overhead. Nếu không có dữ liệu để ghép trước khi timer ACK hết, ACK riêng vẫn phải gửi.",
reasoning:"Bên B sẽ cố kết hợp ACK và dữ liệu trên cùng một chuyến; từ 'cố gắng' rất quan trọng vì không phải lúc nào cũng có dữ liệu chiều ngược.",
options:{a:{why:"Sai. Luôn gửi ACK riêng làm mất lợi ích piggyback.",when:"ACK riêng đúng khi B không có dữ liệu chiều ngược trước thời hạn gửi ACK."},b:{why:"Đúng. Piggyback đưa thông tin ACK vào header của data frame B→A khi có thể.",when:"Đúng khi B có dữ liệu sắp gửi về A trong khoảng chờ ACK cho phép."},c:{why:"Sai về mục tiêu: piggyback thường chờ dữ liệu để ghép ACK, không phải gửi ACK trước rồi cố ý chờ mới gửi data.",when:"Có thể xảy ra trong hoạt động bình thường nếu ACK phải gửi ngay và dữ liệu ứng dụng chỉ phát sinh sau đó, nhưng đó không phải piggyback."},d:{why:"Sai vì gửi data rồi cố ý chờ ACK tách riêng bỏ mất cơ hội mang ACK cùng data.",when:"ACK trễ chỉ hợp lý trong một số delayed-ACK policy, nhưng nếu đã có data chiều ngược thì thường có thể piggyback."}},commonMistakes:["Hiểu piggyback là luôn luôn ghép, trong khi nó phụ thuộc có dữ liệu chiều ngược kịp thời."],summary:"Piggyback = nếu có data chiều ngược, mang ACK cùng data; nếu không thì gửi ACK riêng đúng hạn."},
"De01-18-17":{
knowledge:"Random access protocols điển hình gồm ALOHA, Slotted ALOHA, CSMA, CSMA/CD/CA. CDMA là kỹ thuật đa truy nhập phân chia theo mã, cấp các mã khác nhau để tách người dùng, không thuộc nhóm random-access theo phân loại câu hỏi.",
reasoning:"Ba lựa chọn A, C, D là random access; CDMA là lựa chọn không thuộc nhóm.",
options:{a:{why:"CSMA/CD là random access: các trạm tự tranh quyền truy nhập và xử lý collision.",when:"Đúng nếu hỏi giao thức truy nhập ngẫu nhiên Ethernet chia sẻ."},b:{why:"Đây là đáp án cần chọn cho câu 'không phải'. CDMA phân biệt user bằng spreading code, thuộc channelization/code division.",when:"Đúng nếu hỏi phương pháp phân chia tài nguyên theo mã hoặc kỹ thuật channelization."},c:{why:"Slotted ALOHA là random access; trạm chỉ được bắt đầu phát tại ranh giới slot nhưng vẫn có thể collision.",when:"Đúng nếu hỏi random access có đồng bộ khe."},d:{why:"Pure ALOHA là random access không chia slot; trạm phát khi có frame và retransmit ngẫu nhiên khi collision.",when:"Đúng nếu hỏi random access đơn giản không đồng bộ slot."}},commonMistakes:["Nhầm mọi kỹ thuật 'multiple access' đều là random access."],summary:"Random access: ALOHA/CSMA; CDMA là code-division channelization."},
"De01-19-18":{
knowledge:"Trong kiến trúc phân tầng, Service mô tả những chức năng/tác vụ mà một thực thể/tầng cung cấp cho khách hàng/tầng trên; Protocol mô tả quy tắc giữa peer; interface mô tả cách gọi service.",
reasoning:"Phương án b nói 'những gì máy chủ có thể cung cấp cho khách hàng', phù hợp khái niệm service.",
options:{a:{why:"Sai vì mô tả cách hai thành phần giao tiếp với nhau, tức protocol.",when:"Đúng nếu câu hỏi hỏi định nghĩa giao thức."},b:{why:"Đúng. Service trả lời câu hỏi 'cung cấp cái gì' cho người dùng/tầng trên.",when:"Đúng khi hỏi khái niệm dịch vụ trong kiến trúc mạng/client-server."},c:{why:"Sai vì 'cách sử dụng' nghiêng về interface/API/service primitives.",when:"Đúng nếu hỏi cách client/tầng trên gọi dịch vụ."},d:{why:"Sai vì cách truy cập dịch vụ là interface/access mechanism, không phải bản thân service.",when:"Đúng nếu hỏi service interface/SAP."}},commonMistakes:["Nhầm service với protocol."],summary:"Service = what; Protocol = how peers communicate; Interface = how service is accessed."},
"De01-20-19":{
knowledge:"Trong mô hình client-server, request là thông điệp client→server yêu cầu server thực hiện thao tác/tính toán/cung cấp tài nguyên; response là server→client trả kết quả/trạng thái.",
reasoning:"Chỉ phương án d có đúng hướng và đúng mục đích của request message.",
options:{a:{why:"Sai vì nói client gửi để 'trả lời' yêu cầu; client gửi request để yêu cầu, không phải response cho chính server trong mô tả cơ bản.",when:"Có thể đúng về một thông điệp client→server phản hồi trong một giao thức hai chiều phức tạp, nhưng không phải định nghĩa request client-server."},b:{why:"Sai vì server→client để trả lời là response message.",when:"Đúng nếu câu hỏi hỏi mô tả response."},c:{why:"Sai vì đảo vai trò: server yêu cầu client thực hiện tác vụ không phải request theo mô hình client-server cơ bản đang định nghĩa.",when:"Có thể xảy ra ở callback/server-push protocol, nhưng không phải định nghĩa request chuẩn của mô hình này."},d:{why:"Đúng. Client gửi request cho server để server xử lý/tính toán/thực hiện tác vụ.",when:"Đúng trong request-response client-server."}},commonMistakes:["Chỉ nhìn từ 'yêu cầu' mà bỏ qua hướng client→server."],summary:"Request: client→server; Response: server→client."},
"De01-22-20":{
knowledge:"End-point có thể được hiểu ở nhiều mức: thiết bị đầu cuối/host và, trong giao tiếp tiến trình, ứng dụng/socket trên host. Theo phạm vi câu hỏi, PC, mainframe và chương trình ứng dụng mạng đều là thực thể ở biên mạng chứ không phải thiết bị chuyển tiếp lõi.",
reasoning:"Vì các lựa chọn a, b, d đều có thể là điểm cuối theo ngữ cảnh tương ứng, chọn 'tất cả các thành phần trên'.",
options:{a:{why:"PC là end system/host điển hình ở biên mạng.",when:"Đúng nếu endpoint được xét ở mức thiết bị/host."},b:{why:"Ứng dụng mạng là endpoint ở mức process/application; giao tiếp transport thực chất là process-to-process.",when:"Đúng nếu endpoint được xét ở mức socket/tiến trình."},c:{why:"Đúng theo ý đề vì cả PC, ứng dụng mạng và máy tính lớn đều có thể đóng vai trò endpoint.",when:"Đúng khi khái niệm endpoint được dùng rộng cho đầu cuối giao tiếp ở biên mạng."},d:{why:"Mainframe/máy tính lớn cũng là host và có thể là đầu cuối của truyền thông.",when:"Đúng nếu endpoint là một hệ thống đầu cuối/host."}},commonMistakes:["Cho rằng endpoint chỉ là PC cá nhân."],summary:"Endpoint là đầu mút giao tiếp, có thể xét ở mức host hoặc process/socket."},
"De01-23-21":{
knowledge:"Liên kết giữa các tòa nhà ngoài trời thường ưu tiên cáp quang vì khoảng cách lớn, băng thông cao, suy hao thấp, miễn nhiễm nhiễu điện từ và không tạo đường dẫn điện giữa hai hệ thống tiếp đất khác nhau.",
reasoning:"Trong các lựa chọn, fiber là lựa chọn điển hình và an toàn nhất cho backbone campus/building-to-building.",
options:{a:{why:"Đúng. Cáp quang rất phù hợp backbone ngoài trời/liên tòa nhà nhờ khoảng cách, băng thông và cách điện.",when:"Đúng khi nối backbone giữa tòa nhà hoặc môi trường nhiều nhiễu/sét/khác điện thế đất."},b:{why:"UTP phổ biến trong nhà, đoạn ngang Ethernet ngắn; ngoài trời/liên tòa nhà cần loại chuyên dụng và vẫn có hạn chế EMI/grounding/khoảng cách.",when:"Đúng nếu hỏi cabling Ethernet trong tòa nhà khoảng cách ngắn và môi trường phù hợp."},c:{why:"Cáp điện thoại được thiết kế cho thoại/DSL, không phải lựa chọn backbone LAN hiện đại giữa tòa nhà.",when:"Đúng nếu hỏi đường thuê bao PSTN/DSL."},d:{why:"Coax từng dùng Ethernet/cable network và có shielding tốt, nhưng không phải lựa chọn thường được ưu tiên hiện nay cho backbone liên tòa nhà so với fiber.",when:"Đúng nếu hỏi mạng cáp truyền hình hoặc Ethernet coax lịch sử/ứng dụng RF."}},commonMistakes:["Chọn UTP vì quen thuộc mà bỏ qua khoảng cách và cách điện giữa tòa nhà."],summary:"Backbone liên tòa nhà: ưu tiên fiber."},
"De01-24-22":{
knowledge:"Trong một môi trường broadcast dùng chung/miền va chạm cổ điển, các nút cùng chia sẻ kênh. Để truyền thành công tại một thời điểm, chỉ một máy được chiếm kênh; nhiều máy phát đồng thời gây tranh chấp/collision tùy MAC.",
reasoning:"Vì vậy số máy được phép truyền thành công đồng thời trên kênh broadcast chia sẻ đang xét là một.",
options:{a:{why:"Sai. Ba trạm cùng phát trên cùng kênh chia sẻ làm tín hiệu chồng lấn/tranh chấp.",when:"Chỉ có thể có ba truyền đồng thời nếu tài nguyên đã được tách thành các kênh độc lập (frequency/code/space), không phải một broadcast channel duy nhất."},b:{why:"Đúng. Một transmitter tại một thời điểm tránh xung đột trên shared medium theo mô hình cơ bản.",when:"Đúng khi các máy cùng chia sẻ một broadcast channel/collision domain."},c:{why:"Sai vì bốn transmitter đồng thời không phù hợp kênh chung không phân chia.",when:"Có thể đúng trong hệ thống có bốn kênh trực giao riêng, ngoài giả thiết câu."},d:{why:"Sai; hai máy phát đồng thời đã đủ tạo collision/tranh chấp trên shared medium.",when:"Có thể đúng nếu full-duplex point-to-point cho phép hai đầu phát đồng thời, nhưng đó không phải broadcast shared medium."}},commonMistakes:["Nhầm broadcast với full-duplex point-to-point."],summary:"Shared broadcast medium: một trạm chiếm kênh tại một thời điểm để truyền thành công."},
"De01-25-23":{
knowledge:"Router chuyển tiếp ở lớp mạng và tối thiểu cần Physical + Data Link + Network cho từng interface. Transport (TCP/UDP) là chức năng end-to-end của host; router trung gian không cần triển khai transport để chuyển tiếp packet thông thường.",
reasoning:"Mệnh đề 'tất cả router phải cài tầng vận chuyển' là sai.",
options:{a:{why:"Sai. Router có thể chạy các tiến trình quản trị/control-plane dùng TCP/UDP, nhưng việc forwarding IP không đòi mọi router phải xử lý transport của lưu lượng đi qua.",when:"Có thể đúng nếu nói một router cụ thể chạy ứng dụng quản trị/dịch vụ cần TCP/UDP cho chính nó, không phải yêu cầu của chức năng router nói chung."},b:{why:"Đúng. Tầng transport thuộc end hosts cho giao tiếp process-to-process; router chủ yếu xử lý tới network layer khi forward.",when:"Đúng khi xét kiến trúc Internet/OSI và chức năng chuyển tiếp chuẩn của router."}},commonMistakes:["Thấy router chạy SSH/BGP rồi suy ra transport là bắt buộc cho mọi packet forwarding."],summary:"Forwarding router không cần transport layer của luồng transit; transport là end-to-end."}
});