window.MANUAL_SOLUTIONS=Object.assign(window.MANUAL_SOLUTIONS||{}, {
"De01-26-24":{
knowledge:"Cửa sổ trượt cho phép tối đa W frame chưa được ACK đồng thời. Với k=3 bit có 2^3=8 số thứ tự (0…7); cửa sổ được thỏa thuận W=4. Nếu 2,3,4 đã gửi và còn chờ ACK thì đang chiếm 3/4 vị trí.",
reasoning:"Còn đúng một slot gửi mới. Theo thứ tự modulo 8, sau 4 là 5, nên frame tiếp theo có thể phát là 5.",
options:{a:{why:"Sai. Frame 4 đã nằm trong tập frame đang gửi/chờ ACK nên không phải frame mới tiếp theo.",when:"4 chỉ là lựa chọn đúng nếu trạng thái cửa sổ hiện tại kết thúc ở 3 và 4 chưa được gửi."},b:{why:"Đúng. Ba frame 2,3,4 đang outstanding; W=4 còn một chỗ và số thứ tự kế tiếp là 5.",when:"Đúng với trạng thái cửa sổ hiện tại và sequence space 0…7."},c:{why:"Sai. Muốn gửi 6 trước hết phải còn ít nhất hai slot mới (cho 5 và 6), nhưng hiện chỉ còn một.",when:"6 có thể được gửi sau khi cửa sổ trượt/ACK giải phóng đủ chỗ và 5 đã được phép đưa vào cửa sổ."},d:{why:"Sai. 7 còn xa hơn mép phải cửa sổ hiện tại, không thể nhảy qua 5 và 6.",when:"7 đúng khi cửa sổ đã trượt đủ xa để 7 nằm trong send window."}},
calculation:{title:"Xác định frame được phép gửi",steps:["k=3 ⇒ sequence number space = 2^3=8 giá trị: 0…7.","W=4 ⇒ tối đa 4 frame chưa ACK.","Outstanding hiện có: 2,3,4 ⇒ 3 frame.","Số slot trống = 4−3=1.","Frame mới kế tiếp sau 4 là 5."],result:"Chỉ frame 5 được phép gửi ngay."},commonMistakes:["Nhầm 2^k là kích thước cửa sổ dù đề đã cho W=4."],summary:"Send window còn 1 slot; next sequence = 5."},
"De01-27-25":{
knowledge:"Lợi ích mạng máy tính gồm chia sẻ tài nguyên, giảm chi phí nhờ dùng chung thiết bị/phần mềm/dữ liệu và tạo ra các ứng dụng/dịch vụ mới. Việc nối mạng không tự làm CPU/RAM của một máy cá nhân nhanh hơn.",
reasoning:"Đề hỏi lợi ích KHÔNG đúng; 'tăng hiệu suất của máy tính cá nhân' không phải lợi ích trực tiếp/đảm bảo của networking.",
options:{a:{why:"Đây có thể là lợi ích: dùng chung máy in, lưu trữ, đường Internet hoặc dịch vụ giúp giảm đầu tư trùng lặp.",when:"Đúng khi tài nguyên đắt tiền được chia sẻ và chi phí mạng thấp hơn chi phí trang bị riêng lẻ."},b:{why:"Đúng là lợi ích: mạng tạo nền tảng cho email, web, cloud, collaboration, distributed apps…",when:"Đúng khi nói khả năng phát triển ứng dụng/dịch vụ phân tán nhờ kết nối."},c:{why:"Đây là đáp án cần chọn. Nối mạng có thể cho máy truy cập tài nguyên xa nhưng không làm bản thân CPU/memory/local compute của máy cá nhân tự tăng hiệu suất; thậm chí networking còn có overhead.",when:"Chỉ có thể nói 'tăng hiệu suất công việc/hệ thống' nếu phân tải hoặc dùng tài nguyên từ xa, nhưng đó khác với tăng hiệu năng nội tại của PC."},d:{why:"Đúng. Chia sẻ hardware/software/data là mục tiêu kinh điển của mạng.",when:"Đúng khi nhiều host dùng chung máy in, file server, ứng dụng hoặc storage."}},commonMistakes:["Đồng nhất hiệu quả sử dụng tài nguyên mạng với tốc độ xử lý nội tại của PC."],summary:"Networking tăng khả năng chia sẻ/kết nối, không tự nâng tốc độ phần cứng của máy cá nhân."},
"De01-28-26":{
knowledge:"ARP (Address Resolution Protocol) phân giải IPv4 đã biết thành địa chỉ liên kết/MAC của next hop trong cùng broadcast domain. RARP lịch sử làm chiều ngược MAC→IP; IP chịu định tuyến; ICMP báo lỗi/điều khiển.",
reasoning:"Câu hỏi hỏi IP→MAC, đúng định nghĩa ARP.",
options:{a:{why:"Sai. IP cung cấp địa chỉ logic và chuyển packet, không phải giao thức truy vấn MAC tương ứng.",when:"IP đúng nếu hỏi giao thức lớp mạng dùng địa chỉ IP/định tuyến packet."},b:{why:"Sai chiều. RARP được thiết kế để một máy biết MAC hỏi địa chỉ IP của mình, không phải IP→MAC.",when:"Đúng nếu đề hỏi giao thức lịch sử ánh xạ MAC→IP; ngày nay DHCP thay thế phần lớn use case đó."},c:{why:"Đúng. Host phát ARP Request hỏi 'ai có IPv4 X', chủ sở hữu trả ARP Reply chứa MAC.",when:"Đúng khi cần tìm MAC của IPv4 next hop trong LAN IPv4."},d:{why:"Sai. ICMP mang thông báo lỗi/chẩn đoán như Echo, Destination Unreachable; không làm address resolution.",when:"Đúng nếu hỏi ping hoặc báo lỗi điều khiển IP."}},commonMistakes:["Nhầm ARP và RARP."],summary:"ARP: IPv4→MAC; RARP lịch sử: MAC→IP."},
"De01-29-27":{
knowledge:"Ảnh đen-trắng nhị phân chỉ có 2 mức. Số bit tối thiểu để biểu diễn N mức là ceil(log2 N); với N=2 cần 1 bit, có thể quy ước 0=đen, 1=trắng hoặc ngược lại.",
reasoning:"Do chỉ hai trạng thái, 1 bit/pixel là đủ.",
options:{a:{why:"Đúng. 1 bit có 2^1=2 mã, vừa đủ cho đen và trắng.",when:"Đúng với ảnh bilevel/monochrome chỉ có đúng hai mức."},b:{why:"Sai cho ảnh nhị phân. 8 bit cho 256 giá trị, thường dùng ảnh grayscale 8-bit hoặc một kênh màu, nhiều hơn yêu cầu.",when:"Đúng nếu ảnh xám có 256 mức (0…255) và dùng 8 bit/pixel."},c:{why:"Sai. 4 bit cho 16 mức, không cần thiết với ảnh chỉ đen/trắng.",when:"Đúng nếu cần mã hóa tối đa 16 mức xám/màu chỉ số."},d:{why:"Sai. 16 bit cho 65.536 giá trị, dư rất nhiều cho hai mức.",when:"Đúng nếu định dạng cần 16 bit/pixel (ví dụ grayscale 16-bit hoặc pixel format cụ thể)."}},calculation:{title:"Tính số bit tối thiểu",steps:["Số mức màu N=2.","Cần b sao cho 2^b ≥ 2.","b=1 là giá trị nhỏ nhất."],result:"1 bit/pixel."},commonMistakes:["Nhầm ảnh đen-trắng nhị phân với ảnh grayscale 8 bit."],summary:"Hai mức ⇒ 1 bit là đủ."},
"De01-30-28":{
knowledge:"TCP receiver quảng cáo receive window (rwnd) để flow control. rwnd=0 nghĩa bộ đệm nhận hiện không còn không gian; sender phải dừng gửi dữ liệu mới (trừ các cơ chế thăm dò zero-window/persist) cho đến khi window mở lại.",
reasoning:"Vì advertised window bằng 0 nên bên gửi tạm dừng truyền payload bình thường.",
options:{a:{why:"Sai. Không có quy tắc gửi thêm 1 KB 'để bắt tay' khi window=0; làm vậy vi phạm flow control.",when:"Sender có thể gửi một zero-window probe rất nhỏ theo persist mechanism, nhưng không phải mặc định 1 KB và không phải bắt tay."},b:{why:"Sai. Tiếp tục gửi data bình thường có thể làm receiver quá tải/buffer overflow và trái rwnd.",when:"Đúng khi receiver quảng cáo cửa sổ dương đủ chứa dữ liệu đang gửi."},c:{why:"Đúng. Sender tạm dừng data do receiver báo không còn receive window; sau đó chờ window update và dùng persist timer/probe để tránh deadlock nếu update mất.",when:"Đúng khi effective receive window bằng 0."},d:{why:"Sai. Zero window là trạng thái flow control tạm thời, không đồng nghĩa kết nối TCP phải đóng.",when:"Ngắt kết nối chỉ đúng khi có FIN/RST hoặc timeout/chính sách ứng dụng dẫn tới đóng, không chỉ vì rwnd=0."}},commonMistakes:["Nhầm zero window với connection failure."],summary:"rwnd=0 ⇒ pause data, duy trì kết nối và chờ/probe để window mở lại."},
"De01-31-29":{
knowledge:"UDP là datagram protocol không kết nối. Header có source port, destination port, length, checksum; UDP không có sequence number, ACK, retransmission hay flow/congestion control tích hợp. Checksum vẫn tồn tại, nên câu ghi 'không kiểm tra lỗi' trong lời chú thích nguồn là quá mạnh.",
reasoning:"Trong các lựa chọn, 'không có báo nhận' mô tả đúng UDP chuẩn.",
options:{a:{why:"Sai. UDP header không có Sequence Number; nếu ứng dụng cần sequencing phải tự thêm ở tầng ứng dụng.",when:"Sequence number đúng nếu hỏi TCP hoặc một giao thức ứng dụng chạy trên UDP tự định nghĩa trường sequence."},b:{why:"Đúng. UDP không gửi ACK ở tầng transport.",when:"Đúng khi nói đặc tính native của UDP."},c:{why:"Sai. UDP không tự retransmit gói mất/lỗi; reliability nếu cần do ứng dụng/giao thức trên UDP thực hiện.",when:"Retransmission đúng khi ứng dụng xây ARQ riêng trên UDP hoặc khi dùng TCP."},d:{why:"Sai vì phương án mở đầu 'Có báo nhận' trái UDP. Phần giải thích đi kèm còn nói UDP không có báo nhận; ngoài ra UDP có checksum nên nói hoàn toàn 'không kiểm tra lỗi' cũng không chuẩn.",when:"'Có báo nhận' chỉ đúng với một protocol/application chạy trên UDP tự định nghĩa ACK, không phải UDP bản thân."}},commonMistakes:["Cho rằng UDP không có checksum; UDP có checksum nhưng không tự phục hồi bằng retransmission."],summary:"UDP: connectionless, no ACK/sequence/retransmission built in; có checksum."},
"De01-32-30":{
knowledge:"Network layer chịu trách nhiệm host-to-host packet delivery qua nhiều liên kết/mạng, bao gồm địa chỉ logic và routing/forwarding. Physical truyền bit; Data Link chuyển frame trên một link; Transport cung cấp process-to-process delivery.",
reasoning:"Mô tả đúng tầng mạng là truyền packet qua một liên mạng.",
options:{a:{why:"Sai vì truyền raw bits trên physical medium là chức năng tầng Physical.",when:"Đúng nếu hỏi chức năng tầng vật lý."},b:{why:"Sai. Process-to-process/message delivery thuộc Transport layer (và ứng dụng xây message semantics), không phải Network.",when:"Đúng nếu hỏi chức năng tầng vận chuyển."},c:{why:"Phần 'truyền frame trên một kênh vật lý' thuộc Data Link; nếu phương án OCR ghép thêm câu về packet thì bản thân phương án bị lẫn hai khái niệm, nên không chọn.",when:"Mệnh đề frame trên một link đúng nếu hỏi Data Link."},d:{why:"Đúng. Network layer đưa packet từ mạng nguồn qua routers/liên mạng tới mạng đích.",when:"Đúng khi hỏi chức năng layer 3."}},commonMistakes:["Nhầm PDU: Physical=bit, Data Link=frame, Network=packet, Transport=segment/datagram."],summary:"Network layer = packet delivery/routing across internetwork."},
"De01-33-31":{
knowledge:"Trong IEEE 802, tầng Data Link của mô hình OSI thường được tách thành LLC (Logical Link Control) và MAC (Media Access Control). MAC xử lý truy nhập môi trường/địa chỉ MAC; LLC cung cấp giao diện logic cho tầng trên và multiplex protocol.",
reasoning:"Vì vậy đáp án là Liên kết dữ liệu.",
options:{a:{why:"Sai. Network layer không phải tầng được IEEE 802 chia thành LLC/MAC.",when:"Network đúng nếu hỏi IP/routing/packet layer."},b:{why:"Sai. Transport không chia thành LLC/MAC.",when:"Transport đúng nếu hỏi TCP/UDP/end-to-end transport."},c:{why:"Đúng. Data Link được mô hình IEEE 802 chia LLC và MAC.",when:"Đúng khi hỏi cấu trúc tầng liên kết của LAN IEEE 802."},d:{why:"Sai. Physical có các đặc tả PHY nhưng LLC/MAC không phải hai tầng con của Physical.",when:"Physical đúng nếu hỏi tín hiệu/mã đường truyền/media interface."}},commonMistakes:["Đặt MAC ở Physical thay vì Data Link."],summary:"IEEE 802 Data Link = LLC + MAC."},
"De01-34-32":{
knowledge:"Mã Morse (dấu chấm/gạch, 'tít/te') gắn lịch sử với hệ thống điện báo/telegraph. Điện thoại chủ yếu truyền thoại; mạng máy tính dùng nhiều encoding khác.",
reasoning:"Từ khóa Morse xác định trực tiếp mạng điện báo.",
options:{a:{why:"Đúng. Telegraph truyền ký tự bằng chuỗi tín hiệu Morse trong các hệ thống cổ điển.",when:"Đúng khi hỏi hệ thống lịch sử sử dụng Morse."},b:{why:"Sai. Mạng điện thoại ban đầu truyền tín hiệu thoại liên tục, không dùng Morse làm cơ chế mã hóa chung.",when:"Đúng nếu hỏi hạ tầng truyền tiếng nói/PSTN."},c:{why:"Sai. 'Mạng hướng đầu cuối' không phải tên hệ thống đặc thù dùng Morse.",when:"Chỉ phù hợp nếu câu hỏi định nghĩa một kiến trúc network riêng, không liên quan Morse."},d:{why:"Sai. Mạng máy tính dùng line coding/modulation/digital encoding khác; Morse không phải chuẩn mã hóa mạng máy tính.",when:"Mạng máy tính đúng nếu hỏi hệ thống truyền dữ liệu số giữa computer hosts."}},commonMistakes:["Thấy Morse là mã nhị phân rồi suy ra mạng máy tính."],summary:"Morse là đặc trưng lịch sử của telegraph."},
"De01-35-33":{
knowledge:"Routing phân tán nghĩa mỗi router tham gia tính toán/chọn đường dựa trên thông tin cục bộ và thông tin trao đổi với router khác; không có một bộ điều khiển duy nhất tính tất cả route. 'Động' nói route tự cập nhật theo trạng thái, còn 'phân tán' nói nơi thực hiện tính toán.",
reasoning:"Đề nhấn mạnh 'mỗi router phải tự tính toán tìm kiếm thông tin', nên phân loại đúng là chọn đường phân tán.",
options:{a:{why:"Đúng. Mỗi router tự chạy thuật toán/duy trì state và trao đổi routing information để tính next hop.",when:"Đúng khi routing computation phân bố trên nhiều router, ví dụ nhiều giao thức truyền thống."},b:{why:"Sai. Static routing do quản trị cấu hình và không hàm ý mỗi router tự khám phá đường.",when:"Đúng nếu route được cấu hình thủ công và không tự thay đổi theo topology."},c:{why:"Có thể routing phân tán đồng thời là động, nhưng 'động' không trả lời đúng đặc điểm được hỏi về vị trí tính toán. Câu muốn đối lập distributed với centralized.",when:"Đúng nếu đề hỏi route có tự thích nghi/cập nhật khi topology thay đổi hay không."},d:{why:"Sai. Centralized routing có một điểm/hệ thống trung tâm tính toán hoặc có toàn cục rồi phân phối quyết định, trái 'mỗi router tự tính'.",when:"Đúng nếu controller trung tâm có network-wide view và tính đường cho thiết bị."}},commonMistakes:["Nhầm hai trục phân loại: static/dynamic và centralized/distributed."],summary:"Mỗi router tự tính ⇒ distributed routing."},
"De01-36-34":{
knowledge:"CRC với generator P=1001 có 4 bit nên bậc r=3. Nối 3 số 0 vào M=101010 rồi chia modulo-2 cho 1001; remainder 3 bit được nối vào M để tạo codeword.",
reasoning:"Phép chia XOR cho remainder F=111, nên T=101010111.",
options:{a:{why:"Đúng. 111 là phần dư của 101010000 ÷ 1001 theo modulo-2.",when:"Đúng với chính M=101010 và generator=1001."},b:{why:"Sai. 001 không phải remainder; codeword 101010001 chia 1001 sẽ còn dư khác 0 ở receiver.",when:"001 chỉ đúng nếu phép chia với một message/generator khác cho remainder 001."},c:{why:"Sai. Remainder 011 không thu được từ phép chia XOR của dữ kiện này.",when:"Đúng nếu một bài CRC khác cho remainder 011."},d:{why:"Sai. Remainder 100 không đúng với M,P đã cho.",when:"Đúng nếu dữ kiện khác tạo remainder 100."}},calculation:{title:"CRC modulo-2",steps:["P=1001 ⇒ r=4−1=3.","Append 3 zero: 101010000.","Chia XOR 101010000 cho 1001.","Các bước XOR lần lượt loại bit 1 đầu; phần dư cuối = 111.","Codeword T = M || F = 101010 || 111."],result:"T=101010111."},commonMistakes:["Dùng phép trừ/chia thập phân thay vì XOR modulo-2."],summary:"CRC = remainder 111; gửi 101010111."},
"De01-37-35":{
knowledge:"Directed broadcast của một subnet có toàn bộ bit host bằng 1; network address có toàn bộ bit host bằng 0. Phần network giữ nguyên theo prefix, không phải tất cả network bits bằng 0/1.",
reasoning:"Phương án c đúng định nghĩa broadcast address trong subnet.",
options:{a:{why:"Sai. Điều kiện broadcast không yêu cầu network bits đều 1 và host bits 0; host bits 0 lại là đặc trưng network address.",when:"Không phải quy tắc broadcast; một pattern cụ thể có thể tình cờ có network bits 1 nhưng không phải định nghĩa."},b:{why:"Sai. Network bits không phải tất cả 0; chúng mang prefix của subnet. Host bits 1 là đúng nhưng nửa đầu phát biểu sai.",when:"Host bits=1 là điều kiện đúng nếu giữ nguyên prefix mạng thực tế."},c:{why:"Đúng. Giữ phần network theo subnet và đặt mọi host bit=1 tạo directed broadcast tới các host trong subnet (trong mô hình IPv4 truyền thống).",when:"Đúng khi hỏi broadcast address của một IPv4 subnet có broadcast."},d:{why:"Sai cho broadcast nhưng mô tả network address: all host bits=0 xác định subnet.",when:"Đúng nếu câu hỏi hỏi địa chỉ mạng/network address."}},commonMistakes:["Nhầm network address (host=0) với broadcast (host=1)."],summary:"Subnet: host bits all 0 = network; all 1 = broadcast."},
"De01-38-36":{
knowledge:"Transport layer của Internet dùng chủ yếu TCP và UDP. IP thuộc Network layer. Do đó lựa chọn chứa cả TCP và UDP, không kèm IP, là đúng.",
reasoning:"TCP và UDP đều là layer 4; IP là layer 3.",
options:{a:{why:"Sai vì UDP là transport nhưng IP là network; cặp không cùng thuộc tầng vận chuyển.",when:"Đúng nếu hỏi một cặp giao thức ở hai tầng Network+Transport cụ thể, không phải 'đều ở Transport'."},b:{why:"Sai. IP thuộc Network layer.",when:"Đúng nếu hỏi giao thức lớp mạng Internet."},c:{why:"Sai vì TCP là transport còn IP là network.",when:"Đúng nếu hỏi protocol stack IP+TCP chứ không hỏi cùng tầng."},d:{why:"Đúng. TCP và UDP đều cung cấp transport process-to-process bằng port numbers với semantics khác nhau.",when:"Đúng khi hỏi giao thức tầng vận chuyển Internet."}},commonMistakes:["Thấy TCP/IP là một cụm rồi cho IP thuộc Transport."],summary:"Layer 4: TCP, UDP; Layer 3: IP."},
"De01-39-37":{
knowledge:"MAC address là địa chỉ lớp 2 dùng trên LAN. NIC thường có một địa chỉ được nhà sản xuất gán (burned-in/universal address), nhưng hệ điều hành/driver có thể cấu hình locally administered MAC để override trong nhiều hệ thống.",
reasoning:"Theo ý cơ bản của đề, A là mô tả chuẩn nhất: MAC là layer-2 address gắn với network interface. Cần hiểu 'gắn cứng' là simplification, không phải tuyệt đối không đổi được.",
options:{a:{why:"Đúng theo mô hình giáo trình: MAC là địa chỉ lớp 2 gắn với card/interface mạng và được Ethernet dùng để chuyển frame.",when:"Đúng khi hỏi bản chất/layer của MAC hoặc địa chỉ phần cứng mặc định của NIC."},b:{why:"Sai. Địa chỉ lớp 3 do router dùng để định tuyến là IP, không phải MAC.",when:"Đúng nếu thay 'MAC' bằng 'IP address'."},c:{why:"Sai. DHCP chủ yếu cấp cấu hình lớp 3 như IP, mask, gateway, DNS; không cấp factory MAC cho NIC.",when:"Đúng nếu câu hỏi hỏi cách host tự động nhận IPv4 configuration."},d:{why:"Không chọn vì đây không phải định nghĩa MAC. Nhiều driver/OS thực tế cho phép override/spoof MAC bằng locally administered address, nhưng điều đó không biến MAC thành địa chỉ lớp 3 hay địa chỉ 'được Windows phát'.",when:"Mệnh đề có thể đúng về khả năng cấu hình MAC override trên một số adapter/driver, nhưng không phải thuộc tính định nghĩa của MAC address."}},commonMistakes:["Học 'MAC không bao giờ đổi' quá tuyệt đối; phân biệt factory MAC với locally administered override."],summary:"MAC là L2 interface address; mặc định thường do NIC/vendor gán, nhưng có thể override ở phần mềm."},
"De01-40-38":{
knowledge:"Token Ring/token passing là controlled access: quyền truyền nằm ở token và tuần tự đi qua các trạm, vì vậy có thể đặt cận trên cho thời gian chờ dựa vào thời gian quay vòng token và số trạm. ALOHA/CSMA/CSMA-CD là contention/random access nên thời gian chờ do collision/backoff không có bound tương tự.",
reasoning:"Token Ring cho truy nhập xác định hơn và có thể tính worst-case access delay.",
options:{a:{why:"Sai. CSMA phụ thuộc kênh bận và tranh chấp; không đảm bảo một thời gian chờ tối đa hữu hạn đơn giản trong mô hình ngẫu nhiên.",when:"Đúng nếu hỏi giao thức nghe kênh trước khi phát."},b:{why:"Sai. ALOHA có collision và retransmission ngẫu nhiên; delay có thể kéo dài tùy số lần va chạm.",when:"Đúng nếu hỏi random access đơn giản."},c:{why:"Đúng. Với token circulation có thứ tự, trạm biết sẽ được token sau một vòng tối đa trong điều kiện hệ thống chuẩn.",when:"Đúng khi hỏi bounded/deterministic medium access."},d:{why:"Sai. CSMA/CD giảm/giải quyết collision nhưng exponential backoff vẫn mang tính ngẫu nhiên, không giống token-passing bound.",when:"Đúng nếu hỏi Ethernet half-duplex collision detection."}},commonMistakes:["Cho rằng carrier sense làm CSMA deterministic."],summary:"Token passing ⇒ controlled, bounded access; contention protocols ⇒ không có bound tương tự."},
"De01-41-39":{
knowledge:"Một parity bit phát hiện mọi mẫu lỗi làm đổi parity, tức mọi lỗi có số bit bị lật là lẻ; lỗi có số bit lật chẵn có thể không bị phát hiện. Vì xác suất số bit lỗi lẻ/chẵn phụ thuộc mô hình lỗi, không có phần trăm cố định chung.",
reasoning:"Các đáp án 12%,88%,2%,10% đều bịa một tỷ lệ cố định; đáp án sửa 'Không có tỷ lệ cố định' mới đúng.",
options:{a:{why:"Sai. Không có định luật parity luôn phát hiện 12% lỗi.",when:"12% chỉ có thể là kết quả của một mô hình xác suất lỗi cụ thể được đề cung cấp; câu này không có dữ kiện như vậy."},b:{why:"Sai. 88% cũng không phải tỷ lệ phổ quát.",when:"Chỉ đúng nếu tính từ một phân phối lỗi cụ thể cho xác suất odd-bit errors =0,88."},c:{why:"Sai. 2% không có cơ sở từ cơ chế parity.",when:"Chỉ có thể đúng từ dữ kiện xác suất riêng của một bài khác."},d:{why:"Sai và là đáp án gốc đã được sửa. Parity không chỉ phát hiện '10%' cố định.",when:"10% chỉ đúng nếu một bài xác suất cụ thể tính ra như vậy."},x:{why:"Đúng. Khả năng phát hiện phụ thuộc pattern lỗi; parity đảm bảo phát hiện mọi odd-number bit flips nhưng bỏ lọt một số even-number flips.",when:"Đúng cho phát biểu tổng quát về parity không kèm error model."}},commonMistakes:["Nhầm 'phát hiện mọi lỗi 1 bit' với một phần trăm cố định của mọi lỗi có thể xảy ra."],summary:"Parity có tính chất theo số bit lật, không có % phát hiện cố định nếu chưa cho mô hình lỗi."},
"De01-42-40":{
knowledge:"IEEE 802 Data Link gồm MAC và LLC. MAC tập trung framing, physical addressing/media access và error detection cơ bản; LLC cung cấp logical link services, multiplex protocol và trong một số mode có flow/error control.",
reasoning:"Theo phân chia của giáo trình, điều khiển luồng không thuộc chức năng MAC mà thuộc LLC/logic link.",
options:{a:{why:"Không chọn. MAC frame có FCS/CRC nên phát hiện lỗi frame là chức năng MAC cơ bản; chuỗi OCR 'Kiểm tra lỗi b Điều khiển luồng' bị dính chữ nhưng phần kiểm tra lỗi vẫn thuộc MAC.",when:"Đúng nếu hỏi MAC có phát hiện lỗi frame bằng FCS/CRC hay không."},b:{why:"Đúng cho câu phủ định. Flow control không phải chức năng cốt lõi của MAC sublayer trong phân chia này; nó nằm ở LLC/higher protocols tùy chuẩn.",when:"Đúng nếu hỏi chức năng thuộc LLC nhưng không thuộc MAC."},c:{why:"Không chọn. Media access control chính là chức năng định danh của MAC sublayer.",when:"Đúng nếu hỏi MAC làm gì trên shared medium."},d:{why:"Không chọn vì nội dung này là ghi chú giải thích: MAC làm truy nhập/định khung/error detection cơ bản, LLC làm flow control/logical services. Nó củng cố B chứ không phải một lựa chọn chức năng đơn lẻ phù hợp câu hỏi.",when:"Phần mô tả đúng khi so sánh MAC và LLC."}},commonMistakes:["Nhầm mọi flow control ở Data Link đều thuộc MAC."],summary:"MAC: medium access/framing/FCS; LLC: logical link services và flow control theo mô hình giáo trình."},
"De01-43-41":{
knowledge:"Peer-to-peer không có vai trò server/client cố định toàn hệ thống; mỗi peer có thể vừa cung cấp vừa yêu cầu tài nguyên. Domain membership và mô hình dedicated server là đặc trưng khác.",
reasoning:"Phương án a mô tả đúng vai trò ngang hàng và khả năng vừa client vừa server.",
options:{a:{why:"Đúng. Một peer có thể request tài nguyên từ peer khác và đồng thời phục vụ tài nguyên của mình.",when:"Đúng với kiến trúc P2P/decentralized peer roles."},b:{why:"Sai. Gia nhập domain là cơ chế quản trị tập trung (ví dụ Active Directory), không phải điều kiện của P2P.",when:"Đúng nếu hỏi mô hình domain-based network được quản trị tập trung."},c:{why:"Sai vì vẫn tách 'client' và 'server' thành hai nhóm cố định; đó là client-server.",when:"Đúng nếu hỏi kiến trúc client-server."},d:{why:"Sai. Một server cố định và các client khác là mô hình client-server, trái ngang hàng.",when:"Đúng nếu hỏi dedicated server architecture."}},commonMistakes:["Cho rằng P2P nghĩa mọi máy giống phần cứng; thực chất là vai trò giao tiếp ngang hàng."],summary:"P2P: peer có thể vừa client vừa server."},
"De01-44-42":{
knowledge:"Với k bit sequence number có 2^k giá trị. Trong Go-Back-N, để tránh nhập nhằng giữa frame cũ và frame mới sau khi số thứ tự quay vòng, sender window tối đa là 2^k−1.",
reasoning:"Cảnh báo nguồn xác nhận ký hiệu bị mất số mũ và câu được hiểu theo Go-Back-N; do đó chọn 2^k−1.",
options:{a:{why:"Sai. (2^k−1)/2 không phải giới hạn sender window chuẩn của Go-Back-N.",when:"Một giới hạn xấp xỉ nửa sequence space liên quan Selective Repeat, nhưng chuẩn thường là W≤2^(k−1), không biểu thức này."},b:{why:"Sai. W=2^k dùng hết toàn bộ sequence space sẽ gây nhập nhằng frame cũ/mới khi sequence wrap trong GBN.",when:"2^k đúng nếu chỉ hỏi số lượng giá trị sequence number có thể biểu diễn bằng k bit."},c:{why:"Nếu OCR muốn biểu diễn 2^k/2=2^(k−1), đây là giới hạn thường dùng cho Selective Repeat, không phải GBN theo cảnh báo nguồn.",when:"Đúng cho maximum window của Selective Repeat trong điều kiện sender/receiver windows chiếm không quá nửa sequence space."},d:{why:"Đúng. Go-Back-N sender window tối đa 2^k−1.",when:"Đúng khi sequence field có k bit và dùng GBN theo quy tắc chuẩn."}},calculation:{title:"Kích thước cửa sổ GBN",steps:["k bit ⇒ sequence space N=2^k.","GBN phải chừa ít nhất một sequence number ngoài send window để phân biệt vòng cũ/mới.","Wmax=N−1=2^k−1."],result:"Wmax=2^k−1."},commonMistakes:["Dùng giới hạn Selective Repeat 2^(k−1) cho Go-Back-N."],summary:"GBN: W≤2^k−1; SR: thường W≤2^(k−1)."},
"De01-45-43":{
knowledge:"Stop-and-Wait chỉ cho tối đa một frame outstanding: gửi xong phải chờ ACK. Sliding Window cho phép pipeline nhiều frame trước khi ACK của frame đầu quay về, nhờ đó tăng utilization trên đường có propagation delay lớn.",
reasoning:"Điểm khác biệt trực tiếp nhất là khả năng gửi thêm frame khi chưa nhận ACK cho frame trước.",
options:{a:{why:"Sai. Stop-and-Wait cũng có thể dùng sequence bit để phát hiện frame trùng khi ACK mất; chống duplicate không phải khác biệt độc quyền của sliding window.",when:"Đúng nếu nói một thiết kế sliding-window cụ thể dùng sequence numbers để xử lý duplicate, nhưng không phải điểm phân biệt cốt lõi."},b:{why:"Đúng. Sliding Window có nhiều outstanding frames, Stop-and-Wait chỉ một.",when:"Đúng khi so sánh pipeline/window size giữa hai protocol."},c:{why:"Sai. Cả Stop-and-Wait ARQ lẫn sliding-window ARQ đều có cơ chế timeout/retransmission để xử lý ACK mất.",when:"Đúng nếu chỉ hỏi sliding window có thể phục hồi ACK loss hay không, nhưng không phải đặc điểm khác biệt."},d:{why:"Sai. Cả hai đều dùng ACK/timeout để sender biết tình trạng giao hàng.",when:"Đúng nếu hỏi mục tiêu chung của ARQ, không phải khác biệt."}},commonMistakes:["Chọn một chức năng ARQ mà cả hai đều có thay vì pipeline."],summary:"Stop-and-Wait: 1 outstanding; Sliding Window: nhiều outstanding/pipelining."},
"De01-47-44":{
knowledge:"Trong kiến trúc IEEE 802, LLC cung cấp giao diện logic chung phía trên và có thể hoạt động trên nhiều công nghệ MAC/PHY khác nhau (Ethernet, WLAN, token-based theo lịch sử), nên cùng kiểu LLC không bị khóa vào một MAC duy nhất.",
reasoning:"Mệnh đề 'cùng LLC có thể có nhiều tùy chọn MAC' là đúng về nguyên tắc phân tầng/độc lập tương đối giữa sublayers.",
options:{a:{why:"Đúng. Tách LLC khỏi MAC cho phép lớp logic phía trên dùng một giao diện nhất quán trên các công nghệ truy nhập khác nhau.",when:"Đúng khi nói kiến trúc IEEE 802 và tính modular của LLC/MAC."},b:{why:"Sai. Nếu LLC buộc một-một với MAC thì việc tách sublayer và chuẩn hóa interface chung sẽ mất ý nghĩa.",when:"Chỉ đúng với một implementation/protocol stack cụ thể bị giới hạn một MAC, không phải phát biểu kiến trúc tổng quát."}},commonMistakes:["Nhầm LLC và MAC là một protocol duy nhất không thể thay thế."],summary:"LLC có thể nằm trên nhiều MAC implementations."},
"De01-48-45":{
knowledge:"MAC protocol điều phối việc nhiều trạm chia sẻ cùng medium: quyết định ai được truyền/khi nào, xử lý/giảm cạnh tranh và nhằm tránh hoặc giải quyết đồng thời nhiều transmitter trên kênh dùng chung.",
reasoning:"B, C, D đều mô tả các khía cạnh của cùng bài toán medium access, nên A 'Tất cả vấn đề trên' đúng.",
options:{a:{why:"Đúng vì cả ba mục còn lại đều thuộc mục tiêu MAC: sharing, arbitration/competition, và transmission success trên shared medium.",when:"Đúng khi mọi mệnh đề thành phần B/C/D đều đúng trong phạm vi câu hỏi."},b:{why:"Đúng về mục tiêu MAC: điều phối để một transmission thành công trong một collision domain/shared channel tại thời điểm cần độc quyền.",when:"Đúng khi medium không hỗ trợ các truyền đồng thời trực giao."},c:{why:"Đúng. MAC chính là cơ chế cho nhiều node cùng dùng một physical medium theo quy tắc.",when:"Đúng khi hỏi multiple access/shared medium."},d:{why:"Đúng. Tranh chấp/cạnh tranh medium là bài toán cốt lõi của contention MAC hoặc được tránh bằng controlled access.",when:"Đúng trong LAN shared-medium."}},commonMistakes:["Thấy một phương án riêng đúng rồi bỏ qua lựa chọn 'tất cả'."],summary:"MAC giải quyết chia sẻ medium, cạnh tranh và quyền truyền."},
"De01-49-46":{
knowledge:"Flow control có thể dựa trên feedback: receiver gửi thông tin/credit/window cho sender để cho biết có thể gửi thêm bao nhiêu; hoặc rate-based: protocol áp giới hạn tốc độ gửi mà không cần mỗi lần receiver cấp credit trực tiếp.",
reasoning:"Mệnh đề mô tả receiver gửi thông tin về cho sender cho phép gửi thêm và báo trạng thái, đúng kiểu feedback-based.",
options:{a:{why:"Sai. Go-Back-N là ARQ/sliding-window reliability scheme, có feedback nhưng không phải tên phân loại tiếp cận flow control mà câu hỏi yêu cầu.",when:"Đúng nếu hỏi giao thức nào truyền lại từ frame lỗi trở đi."},b:{why:"Sai. Rate-based đặt/điều chỉnh tốc độ gửi; mô tả câu nhấn mạnh thông tin phản hồi trực tiếp từ receiver.",when:"Đúng nếu protocol giới hạn sender theo một rate đã tính/cấu hình thay vì cấp quyền bằng feedback window/credit."},c:{why:"Sai. Selective Repeat là ARQ chỉ retransmit frame mất/lỗi; không phải tên 'feedback-based' trong phân loại này.",when:"Đúng nếu hỏi ARQ nào truyền lại chọn lọc."},d:{why:"Đúng. Receiver feedback (ví dụ advertised window/credit) trực tiếp điều khiển lượng sender được phép phát thêm.",when:"Đúng khi flow control dựa vào trạng thái/capacity do receiver phản hồi."}},commonMistakes:["Nhầm một giao thức cụ thể dùng feedback với tên của loại cơ chế flow control."],summary:"Receiver báo trạng thái/quyền gửi ⇒ feedback-based flow control."},
"De01-50-47":{
knowledge:"Khi đọc sơ đồ TCP phải theo dõi độc lập sequence space của hai chiều. ACK là byte/sequence kế tiếp mong đợi; số ACK tăng theo số byte dữ liệu đã nhận và SYN/FIN tiêu thụ một sequence number.",
reasoning:"Câu phụ thuộc hình trang 10. Theo các trường SEQ/ACK và độ dài segment trong sơ đồ nguồn, phép theo dõi cho Y=4.",
options:{a:{why:"Sai với sơ đồ nguồn: Y không dừng ở 2 sau khi tính phần sequence/data đã được nhận trước điểm đánh dấu.",when:"Y=2 chỉ đúng trong một sơ đồ khác nếu next expected sequence tại điểm đó là 2."},b:{why:"Sai. Giá trị 3 thiếu một đơn vị so với next expected sequence thể hiện trong chuỗi trao đổi của hình.",when:"Y=3 đúng nếu bên nhận đã nhận liên tục tới sequence/byte 2 và đang chờ 3."},c:{why:"Đúng theo hình gốc: sau khi cộng đúng phần sequence space đã tiêu thụ, next expected value là 4.",when:"Đúng với chính sơ đồ source-page-10 và các segment trước vị trí Y."},d:{why:"Sai. 5 sẽ ngụ ý đã tiêu thụ thêm một sequence number/byte so với dữ kiện của hình.",when:"Y=5 đúng nếu trước đó receiver đã nhận liên tục tới 4 (hoặc segment/SYN/FIN làm sequence tiến thêm tương ứng)."}},calculation:{title:"Theo dõi TCP SEQ/ACK trên hình",steps:["Tách hai chiều truyền, không cộng sequence của A vào sequence của B.","Ghi SEQ đầu mỗi segment và số byte dữ liệu/SYN/FIN nó tiêu thụ.","Sau mỗi segment, next expected = SEQ + data length (+1 nếu SYN/FIN liên quan).","Đối chiếu vị trí Y trên source-page-10: next expected value = 4."],result:"Y=4."},commonMistakes:["Không xem ảnh nguồn rồi đoán theo số liền kề.","Quên SYN/FIN chiếm sequence number hoặc cộng nhầm hai chiều."],summary:"Theo sơ đồ gốc trang 10, Y=4; luôn tính ACK từ next expected sequence của chiều đối diện."}
});